/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.patientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Role.CareGiverRole;
import Business.Role.PatientRole;
import Business.Schedule.Task;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.patientFamilyRole.ViewMessageJPanel;

/**
 *
 * @author varsha
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    
    private EcoSystem business;
    
    public PatientWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,Organization organization,Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account= account;
        this.organization = organization;
        this.enterprise = enterprise;
       
        this.business = business;
      
        patientNameJLabel.setText(account.getEmployee().getName());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        patientNameJLabel = new javax.swing.JLabel();
        viewMyScheduleJButton = new javax.swing.JButton();
        solvePuzzlesJButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Welcome ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 90, 30));

        patientNameJLabel.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        add(patientNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 270, 30));

        viewMyScheduleJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        viewMyScheduleJButton.setText("View My Schedule");
        viewMyScheduleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMyScheduleJButtonActionPerformed(evt);
            }
        });
        add(viewMyScheduleJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 200, 40));

        solvePuzzlesJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        solvePuzzlesJButton.setText("Solve Puzzles");
        solvePuzzlesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solvePuzzlesJButtonActionPerformed(evt);
            }
        });
        add(solvePuzzlesJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void viewMyScheduleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMyScheduleJButtonActionPerformed
        // TODO add your handling code here:
        
        ViewMyScheduleJPanel viewMyScheduleJPanel = new ViewMyScheduleJPanel(userProcessContainer, organization, account, business);
       
        userProcessContainer.add("ViewMyScheduleJPanel",viewMyScheduleJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewMyScheduleJButtonActionPerformed

    private void solvePuzzlesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solvePuzzlesJButtonActionPerformed
        // TODO add your handling code here:
       
            
        BrainPuzzlesJPanel brainPuzzleJPanel = new BrainPuzzlesJPanel(userProcessContainer);
       
        userProcessContainer.add("BrainPuzzlesJPanel",brainPuzzleJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_solvePuzzlesJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel patientNameJLabel;
    private javax.swing.JButton solvePuzzlesJButton;
    private javax.swing.JButton viewMyScheduleJButton;
    // End of variables declaration//GEN-END:variables
}
