/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.neurologistRole;

import Business.Organization.NeurologistOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AddTasksForPatient;
import Business.WorkQueue.CaregiverToMedicalPractitioner;
import Business.WorkQueue.GroupChatCommunication;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author varsha
 */
public class ForumJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ForumJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private NeurologistOrganization org;
    public ForumJPanel(JPanel userProcessContainer, UserAccount account, Organization org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.org = (NeurologistOrganization)org;
        populateRequestTable();
    }

    public void populateRequestTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)messageJTable.getModel();
        dtm.setRowCount(0);
        for(WorkRequest req : org.getWorkQueue().getWorkRequestList())
        {
              Object[] row = new Object[2];
              if(req.getSender().getRole().toString().equalsIgnoreCase("CareGiver Role"))
            {
              
                row[0] = req;
                row[1] = req.getSender().getEmployee().getName();
                dtm.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageJTable = new javax.swing.JTable();
        sendJButton = new javax.swing.JButton();
        replyJTextField = new javax.swing.JTextField();
        backJButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Check Messages from caregivers");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 71, 231, 34));

        messageJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "sender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(messageJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 123, -1, 131));

        sendJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        sendJButton.setText("Send");
        sendJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendJButtonActionPerformed(evt);
            }
        });
        add(sendJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 289, 155, 44));
        add(replyJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 289, 191, 44));

        backJButton2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        backJButton2.setText("<< Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });
        add(backJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void sendJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = messageJTable.getSelectedRow();
        if(selectedRow < 0)
           JOptionPane.showMessageDialog(null,"Please select a message");
        
        GroupChatCommunication request = (GroupChatCommunication)messageJTable.getValueAt(selectedRow, 0);
        if(replyJTextField.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter your reply");
        }
        else
        {
        request.setTestResult(replyJTextField.getText());
        
        request.setStatus("Completed");
        }
        
       // populateRequestTable();
        
    }//GEN-LAST:event_sendJButtonActionPerformed

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable messageJTable;
    private javax.swing.JTextField replyJTextField;
    private javax.swing.JButton sendJButton;
    // End of variables declaration//GEN-END:variables
}
