/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.neurologistRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Neurologist.Neurologist;
import Business.Organization.NeurologistOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.PatientFamily.PatientFamily;
import Business.State.State;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientFamilyToNeurologist;
import Business.WorkQueue.WorkRequest;
import Business.city.City;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author varsha
 */
public class PendingTasksNeurologistJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PendingTasksNeurologistJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private NeurologistOrganization org;
    private PatientFamilyToNeurologist request;
    public PendingTasksNeurologistJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, Organization org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.org = (NeurologistOrganization)org;
      //  this.request = request;
        populateTable();
    }

    public void populateTable()
    {
       DefaultTableModel model = (DefaultTableModel) appointmentDetailsJTable.getModel();
       model.setRowCount(0);
       
       // for (WorkRequest request : org.getWorkQueue().getWorkRequestList()) {
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
           // if(request instanceof PatientFamilyToNeurologist ){
            //String rcvrName =  request.getReceiverName();
           // if (rcvrName.equalsIgnoreCase(account.getEmployee().getName())) {
                Object[] row = new Object[3];
                if(request instanceof  PatientFamilyToNeurologist)
                {
                 row[0] = ((PatientFamilyToNeurologist) request).getPatientName();
                 row[1] = ((PatientFamilyToNeurologist) request).getD();
                 row[2] = ((PatientFamilyToNeurologist) request).getTimeSlot();
                }
                
               // for (PatientFamily pf : org.getPatientFamilyDirectory().getPatientFamilyList()) {
               //     for (Patient p : org.getPatientDirectory().getPatientList()) {

                   //     if ((p.getName().equalsIgnoreCase(pf.getPatient().getName()))
                    //            && (pf.getMemberName().equalsIgnoreCase(request.getSender().getEmployee().getName()))) {

                           // row[0] = p.getName();
                          // row[0] =   ((PatientFamilyToNeurologist) request).getPatientName();
                         //   row[1] = ((PatientFamilyToNeurologist) request).getD();
                          //  row[2] = ((PatientFamilyToNeurologist) request).getTimeSlot();
                        //  row[1] =  request.getD();
                     
                            model.addRow(row);
                        }
                    }

                    


        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentDetailsJTable = new javax.swing.JTable();
        backJButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("List of Appointments:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 86, 176, 29));

        appointmentDetailsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Appointment Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(appointmentDetailsJTable);
        if (appointmentDetailsJTable.getColumnModel().getColumnCount() > 0) {
            appointmentDetailsJTable.getColumnModel().getColumn(0).setResizable(false);
            appointmentDetailsJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 150, 490, 172));

        backJButton5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        backJButton5.setText("<< Back");
        backJButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton5ActionPerformed(evt);
            }
        });
        add(backJButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 11, -1, 29));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton5ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appointmentDetailsJTable;
    private javax.swing.JButton backJButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
