/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicalinterface;

import business.Vendor;
import business.VendorCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author varsha
 */
public class CreateVendorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVendorJPanel
     */
    private JPanel userProcessContainer;
    private VendorCatalog vendorCatalog;
    
    CreateVendorJPanel(JPanel userProcessContainer, VendorCatalog vendorCatalog) {
      initComponents();
      this.userProcessContainer = userProcessContainer;
      this.vendorCatalog = vendorCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblVendorName = new javax.swing.JLabel();
        txtVendorName = new javax.swing.JTextField();
        lblVendorEmail = new javax.swing.JLabel();
        txtVendorEmail = new javax.swing.JTextField();
        btnAddVendor = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtVendorID = new javax.swing.JTextField();

        btnBack.setText("<< BACK");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD VENDOR DETAILS");

        lblVendorName.setText("Vendor Name:");

        txtVendorName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVendorNameFocusLost(evt);
            }
        });

        lblVendorEmail.setText("Vendor Email:");

        txtVendorEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVendorEmailFocusLost(evt);
            }
        });

        btnAddVendor.setText("ADD VENDOR");
        btnAddVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVendorActionPerformed(evt);
            }
        });

        btnBack1.setText("<< BACK");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Vendor ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(lblVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtVendorName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(lblVendorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddVendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVendorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtVendorID))))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendorID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVendorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVendorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAddVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
                userProcessContainer.remove(this);              
                CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void txtVendorNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVendorNameFocusLost
        // TODO add your handling code here:
        String fname=txtVendorName.getText();
            if(fname.matches(".*\\d.*"))
            {
              
            JOptionPane.showMessageDialog(null,"You cannot enter Numbers in Name.");
            txtVendorName.setText("");
        
            }
            int i;
        for(i=0; i<fname.length();i++)
        {
            if(fname.charAt(i)=='*' //if first name contains special characters
                    ||fname.charAt(i)=='/'
                    ||fname.charAt(i)=='@'
                    ||fname.charAt(i)=='!'
                    ||fname.charAt(i)=='#'
                    ||fname.charAt(i)=='%'
                    ||fname.charAt(i)=='$'
                    ||fname.charAt(i)=='('
                    ||fname.charAt(i)==')'
                    ||fname.charAt(i)=='_'
                    ||fname.charAt(i)=='.'
                    ||txtVendorName.getText().trim().isEmpty()
                    )
                {
              JOptionPane.showMessageDialog(null,"You cannot enter special characters or whitespaces!");
              txtVendorName.setText("");
              break;
             
            }
        }
    }//GEN-LAST:event_txtVendorNameFocusLost

    private void txtVendorEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVendorEmailFocusLost
        // TODO add your handling code here:
        String eid=txtVendorEmail.getText();
        int countAt=0;
        for ( int i=0; i< eid.length();i++)
        {
            if(eid.charAt(i)=='@')
            {
                countAt++;
            }
        }
       
        String str= eid.substring(eid.indexOf('@')+1,eid.length());
        int countP=0;
        for(int i=0 ; i<str.length();i++)
        {
            if(str.charAt(i)=='.')
            {
                countP++;
            }
        }
        if(countP!=1 ||countAt!=1||eid.startsWith(".")||eid.startsWith("@")||txtVendorEmail.getText().trim().isEmpty())
        {
           JOptionPane.showMessageDialog(null,"Enter valid email id!");
           txtVendorEmail.setText("");
        }
    }//GEN-LAST:event_txtVendorEmailFocusLost

    private void btnAddVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVendorActionPerformed
        // TODO add your handling code here:
       if(!validateEmpty())
       {
          createVendor(); 
       }
    }//GEN-LAST:event_btnAddVendorActionPerformed
 public void clear()
    {
        txtVendorName.setText("");
        txtVendorEmail.setText("");
        txtVendorID.setText("");
    }
public boolean validateEmpty()
    {
      String firstName= txtVendorName.getText();
        //System.out.println(firstName);
        if(firstName.trim().isEmpty()
                ||(txtVendorEmail.getText().trim().isEmpty()
                ||txtVendorID.getText().trim().isEmpty()))
               
        {
          JOptionPane.showMessageDialog(null,"Fields cannot be blank");
          return true;
        }
        else
        {
            
            return false;
        }   
    }
public void createVendor()
{
     String vendorName = txtVendorName.getText();
        String vendorMail = txtVendorEmail.getText();
        String vendorID = txtVendorID.getText();
        
        Vendor vendor = vendorCatalog.addVendor();
       
          vendor.setVendorName(vendorName);
        vendor.setVendorMail(vendorMail);
        vendor.setVendorID(vendorID);
    //    if(vendor.getVendorName().equals(txtVendorName.getText()))
//{
 //   vendorCatalog.removeVendor(vendor);
//}
        JOptionPane.showMessageDialog(null,"Vendor added successfully!!");
        clear(); 
       
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVendor;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblVendorEmail;
    private javax.swing.JLabel lblVendorName;
    private javax.swing.JTextField txtVendorEmail;
    private javax.swing.JTextField txtVendorID;
    private javax.swing.JTextField txtVendorName;
    // End of variables declaration//GEN-END:variables
}
