/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicalinterface;

import business.Product;
import business.ProductCatalog;
import business.Vendor;
import business.VendorCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author varsha
 */
public class CreateNewProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewProductJPanel
     */
    private JPanel userProcessContainer;
     private ProductCatalog productCatalog;
     private Double price; 
     private Double cprice;
     private Double fprice;
    //private Vendor vendor;

    CreateNewProductJPanel(JPanel userProcessContainer, ProductCatalog productCatalog) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
      // this.vendor=vendor;
        this.productCatalog= productCatalog;
        //txtVendorName.setText(vendor.getVendorName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProdFeature = new javax.swing.JTextArea();
        txtProdName = new javax.swing.JTextField();
        txtProdDesc = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtVendorName = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        btnAddProd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCeilPrice = new javax.swing.JTextField();
        txtFloorPrice = new javax.swing.JTextField();

        jLabel1.setText("Product Name:");

        jLabel2.setText("Product description:");

        jLabel3.setText("Price:");

        jLabel4.setText("Vendor Name:");

        jLabel5.setText("Model Number:");

        jLabel6.setText("Product Features: ");

        txtProdFeature.setColumns(20);
        txtProdFeature.setRows(5);
        jScrollPane1.setViewportView(txtProdFeature);

        txtProdName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProdNameFocusLost(evt);
            }
        });
        txtProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdNameActionPerformed(evt);
            }
        });

        txtProdDesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProdDescFocusLost(evt);
            }
        });

        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });

        txtVendorName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVendorNameFocusLost(evt);
            }
        });

        txtModelNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModelNumberFocusLost(evt);
            }
        });

        btnAddProd.setText("ADD PRODUCT");
        btnAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADD PRODUCT DETAILS");

        btnBack1.setText("<< BACK");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Product Type:");

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer", "Printer", "HW Parts", "SW Parts" }));

        jLabel9.setText("Floor Price:");

        jLabel10.setText("Ceil Price:");

        txtCeilPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCeilPriceFocusLost(evt);
            }
        });

        txtFloorPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFloorPriceFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVendorName, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(txtModelNumber)
                                    .addComponent(txtPrice)
                                    .addComponent(txtProdDesc)
                                    .addComponent(txtProdName)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(typeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCeilPrice)
                                    .addComponent(txtFloorPrice)))
                            .addComponent(btnAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCeilPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFloorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
                userProcessContainer.remove(this);            
                CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdActionPerformed
        // TODO add your handling code here:
        if(!validateEmpty())
       {
          create(); 
       }
    }//GEN-LAST:event_btnAddProdActionPerformed
    
    public boolean validateEmpty()
    {
      String firstName= txtProdName.getText();
        //System.out.println(firstName);
        if(firstName.trim().isEmpty()
                ||(txtProdDesc.getText().trim().isEmpty())
                ||(txtVendorName.getText().trim().isEmpty())
                ||(txtModelNumber.getText().trim().isEmpty())
                ||(txtPrice.getText().trim().isEmpty())
                ||(txtProdFeature.getText().trim().isEmpty()))
               
               // ||JYear.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Fields cannot be blank");
          return true;
        }
        else
        {
            
            return false;
        }   
    }
    public void create()
    {
        String prodName = txtProdName.getText();
        String prodDesc = txtProdDesc.getText();
        String modelNumber = txtModelNumber.getText();
        String vendorName = txtVendorName.getText();
        
       //String test = vendor.getVendorName();
       //System.out.println(test);
       //// cprice = Double.parseDouble(txtCeilPrice.getText());
       // fprice = Double.parseDouble(txtFloorPrice.getText());
       //String vendorName = txtVendorName.getText();
        String prodFeature = txtProdFeature.getText();
        String item= (String)typeCombo.getSelectedItem();
        
        Product product = productCatalog.addProduct();
        
        product.setProdName(prodName);
        product.setBasePrice(price);
        product.setModelNumber(modelNumber);
        product.setProdDesc(prodDesc);
        product.setVendorName( vendorName);
        product.setProdFeature(prodFeature);
        product.setType(item);
        product.setCeilPrice(cprice);
        product.setFloorPrice(fprice);
        
        JOptionPane.showMessageDialog(null,"Product added successfully!!");
        clear();
        
    }
    public void clear()
    {
        txtProdName.setText("");
        txtProdDesc.setText("");
        txtModelNumber.setText("");
        txtVendorName.setText("");
        txtPrice.setText("");
        txtProdFeature.setText("");
        typeCombo.setSelectedIndex(0);
        txtCeilPrice.setText("");
        txtFloorPrice.setText("");
    }
    
    private void txtProdNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProdNameFocusLost
        // TODO add your handling code here:
        String fname=txtProdName.getText();
           
            int i;
        for(i=0; i<fname.length();i++)
        {
            if(fname.charAt(i)=='*' //if first name contains special characters
                    ||fname.charAt(i)=='/'
                    ||fname.charAt(i)=='@'
                    ||fname.charAt(i)=='!'
                    ||fname.charAt(i)=='#'
                    ||fname.charAt(i)=='%'
                    ||fname.charAt(i)=='$'
                    ||fname.charAt(i)=='('
                    ||fname.charAt(i)==')'
                    ||fname.charAt(i)=='_'
                    ||fname.charAt(i)=='.'
                    ||txtProdName.getText().trim().isEmpty()
                    )
                {
              JOptionPane.showMessageDialog(null,"You cannot enter special characters or whitespaces!");
              txtProdName.setText("");
              break;
             
            }
        }
    }//GEN-LAST:event_txtProdNameFocusLost

    private void txtProdDescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProdDescFocusLost
        // TODO add your handling code here:
        String dname=txtProdDesc.getText();
            if(dname.matches(".*\\d.*"))
            {
              
            JOptionPane.showMessageDialog(null,"You cannot enter Numbers in Name.");
            txtProdDesc.setText("");
        
            }
            int i;
        for(i=0; i<dname.length();i++)
        {
            if(dname.charAt(i)=='*' //if first name contains special characters
                    ||dname.charAt(i)=='/'
                    ||dname.charAt(i)=='@'
                    ||dname.charAt(i)=='!'
                    ||dname.charAt(i)=='#'
                    ||dname.charAt(i)=='%'
                    ||dname.charAt(i)=='$'
                    ||dname.charAt(i)=='('
                    ||dname.charAt(i)==')'
                    ||dname.charAt(i)=='_'
                    ||dname.charAt(i)=='.'
                    ||txtProdDesc.getText().trim().isEmpty()
                    )
                {
              JOptionPane.showMessageDialog(null,"You cannot enter special characters or whitespaces!");
              txtProdDesc.setText("");
              break;
             
            }
        }
    }//GEN-LAST:event_txtProdDescFocusLost

    private void txtVendorNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVendorNameFocusLost
        // TODO add your handling code here:
         String vname=txtVendorName.getText();
            if(vname.matches(".*\\d.*"))
            {
              
            JOptionPane.showMessageDialog(null,"You cannot enter Numbers in Name.");
           txtVendorName.setText("");
        
            }
            int i;
        for(i=0; i<vname.length();i++)
        {
            if(vname.charAt(i)=='*' 
                    ||vname.charAt(i)=='/'
                    ||vname.charAt(i)=='@'
                    ||vname.charAt(i)=='!'
                    ||vname.charAt(i)=='#'
                    ||vname.charAt(i)=='%'
                    ||vname.charAt(i)=='$'
                    ||vname.charAt(i)=='('
                    ||vname.charAt(i)==')'
                    ||vname.charAt(i)=='_'
                    ||vname.charAt(i)=='.'
                    ||txtVendorName.getText().trim().isEmpty()
                    )
                {
              JOptionPane.showMessageDialog(null,"You cannot enter special characters or whitespaces!");
              txtVendorName.setText("");
              break;
             
            }
        }
    }//GEN-LAST:event_txtVendorNameFocusLost

    private void txtModelNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModelNumberFocusLost
        // TODO add your handling code here:
        String mname=txtModelNumber.getText();
          
            int i;
        for(i=0; i<mname.length();i++)
        {
            if(mname.charAt(i)=='*' //if first name contains special characters
                    ||mname.charAt(i)=='/'
                    ||mname.charAt(i)=='@'
                    ||mname.charAt(i)=='!'
                    
                    ||mname.charAt(i)=='%'
                    ||mname.charAt(i)=='$'
                    ||mname.charAt(i)=='('
                    ||mname.charAt(i)==')'
                    
                    ||mname.charAt(i)=='.'
                    ||txtModelNumber.getText().trim().isEmpty()
                    )
                {
              JOptionPane.showMessageDialog(null,"You cannot enter special characters or whitespaces!");
              txtModelNumber.setText("");
              break;
             
            }
        }
    }//GEN-LAST:event_txtModelNumberFocusLost

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        // TODO add your handling code here:
        try
            {
        if(!txtPrice.getText().trim().isEmpty())
           {
           
        price = Double.parseDouble(txtPrice.getText());
       if(price<fprice || price>cprice)
       {
           JOptionPane.showMessageDialog(null,"Please enter valid price of product between ceil and floor price range!");
           txtPrice.setText("");
       }
        }
            }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,"Please enter valid price of product");
           txtPrice.setText("");
        }
    }//GEN-LAST:event_txtPriceFocusLost

    private void txtProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdNameActionPerformed

    private void txtCeilPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCeilPriceFocusLost
        // TODO add your handling code here:
        try
            {
        if(!txtCeilPrice.getText().trim().isEmpty())
           {
           
        cprice = Double.parseDouble(txtCeilPrice.getText());
      /*  if((cprice<price)||(cprice<fprice))
        {
            JOptionPane.showMessageDialog(null,"Please enter valid ceil price of product");
        }*/
        
        }
            }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,"Please enter valid price of product");
            txtCeilPrice.setText("");
        }
    }//GEN-LAST:event_txtCeilPriceFocusLost

    private void txtFloorPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFloorPriceFocusLost
        // TODO add your handling code here:
        try
            {
        if(!txtFloorPrice.getText().trim().isEmpty())
           {
           
        fprice = Double.parseDouble(txtFloorPrice.getText());
       /* if((fprice>price)||(fprice>cprice))
        {
            JOptionPane.showMessageDialog(null,"Please enter valid ceil price of product");
        }*/
        
        }
            }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,"Please enter valid price of product");
           txtFloorPrice.setText("");
        }
    }//GEN-LAST:event_txtFloorPriceFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProd;
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCeilPrice;
    private javax.swing.JTextField txtFloorPrice;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProdDesc;
    private javax.swing.JTextArea txtProdFeature;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtVendorName;
    private javax.swing.JComboBox<String> typeCombo;
    // End of variables declaration//GEN-END:variables
}
