/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicalinterface;

import business.Product;
import business.ProductCatalog;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author varsha
 */
public class SearchResultJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchResultJPanel
     */
   private JPanel userProcessContainer;
   private ProductCatalog product;

    SearchResultJPanel(JPanel userProcessContainer,ProductCatalog product) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.product = product;
       
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void populateTable() 
    {
        DefaultTableModel dtm=(DefaultTableModel)tblSearchResult.getModel();
        dtm.setRowCount(0);
        for(Product pro : product.getProd())
        {
            Object obj[]= new Object[5];
            obj[0]=pro;
            obj[1]=pro.getProdName();
            obj[2]=pro.getModelNumber();
            obj[3]=pro.getBasePrice();
            obj[4]=pro.getProdDesc();
            dtm.addRow(obj);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblSearch = new javax.swing.JScrollPane();
        tblSearchResult = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSearchFeature = new javax.swing.JTextArea();
        btnViewProductFeatures = new javax.swing.JButton();

        tblSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendor Name", "Product Name", "Model Number", "Price", "product desc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearch.setViewportView(tblSearchResult);
        if (tblSearchResult.getColumnModel().getColumnCount() > 0) {
            tblSearchResult.getColumnModel().getColumn(0).setResizable(false);
            tblSearchResult.getColumnModel().getColumn(1).setResizable(false);
            tblSearchResult.getColumnModel().getColumn(2).setResizable(false);
            tblSearchResult.getColumnModel().getColumn(3).setResizable(false);
            tblSearchResult.getColumnModel().getColumn(4).setResizable(false);
        }

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtSearchFeature.setBackground(new java.awt.Color(204, 204, 255));
        txtSearchFeature.setColumns(20);
        txtSearchFeature.setRows(5);
        txtSearchFeature.setEnabled(false);
        jScrollPane1.setViewportView(txtSearchFeature);

        btnViewProductFeatures.setText("View Product features");
        btnViewProductFeatures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductFeaturesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewProductFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(tblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewProductFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        //userProcessContainer.add("AccountManageWorkAreaJPanel", accountManage);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewProductFeaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductFeaturesActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblSearchResult.getSelectedRow();
        if(selectedRow<0)
        {
          JOptionPane.showMessageDialog(null,"Please select any row!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
        Product prod = (Product)tblSearchResult.getValueAt(selectedRow,0);
        txtSearchFeature.setText(prod.getProdFeature());   
        }
    }//GEN-LAST:event_btnViewProductFeaturesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewProductFeatures;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane tblSearch;
    private javax.swing.JTable tblSearchResult;
    private javax.swing.JTextArea txtSearchFeature;
    // End of variables declaration//GEN-END:variables
}
