/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicalinterface;

import business.Product;
import business.ProductCatalog;
import business.Vendor;
import business.VendorCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author varsha
 */
public class ViewProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewProductJPanel
     */
    private JPanel userProcessContainer;
     private Product product;
    

    ViewProductJPanel(JPanel userProcessContainer, Product product) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
        this.product= product;
        view();
        btnSave.setEnabled(false);
        btnUpdateProduct.setEnabled(true);
        
    }

    
    public void view()
    {
        txtProdName.setText(product.getProdName());
       txtProdDesc.setText(product.getProdDesc());
        txtModelNumber.setText(product.getModelNumber());
        txtPrice.setText(String.valueOf((product.getBasePrice())));
       txtProdFeature1.setText(product.getProdFeature());
        txtVendorName.setText(product.getModelNumber());
        txtType.setText(product.getType());
        txtCeilPrice.setText(String.valueOf(product.getCeilPrice()));
        txtFloorPrice.setText(String.valueOf(product.getFloorPrice()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUpdateProduct = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        txtVendorName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtProdDesc = new javax.swing.JTextField();
        txtProdName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProdFeature1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCeilPrice = new javax.swing.JTextField();
        txtFloorPrice = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack1.setText("<< BACK");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 123, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIEW PRODUCT DETAILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 11, 191, 25));

        btnUpdateProduct.setText("Update Product Details");
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });
        add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 160, 39));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 141, 39));

        jLabel2.setText("Product description:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 128, 26));

        jLabel3.setText("Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 128, 30));

        jLabel4.setText("Vendor Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 128, 30));

        jLabel5.setText("Model Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 128, 29));

        jLabel6.setText("Product Features: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 128, 31));

        txtModelNumber.setEnabled(false);
        add(txtModelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 210, 32));

        txtVendorName.setEnabled(false);
        add(txtVendorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 210, 30));

        txtPrice.setEnabled(false);
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 210, 31));

        txtProdDesc.setEnabled(false);
        add(txtProdDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 210, 26));

        txtProdName.setEnabled(false);
        add(txtProdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 210, 29));

        jLabel7.setText("Product Name:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 128, 29));

        jLabel8.setText("Product Type:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 128, 22));

        txtType.setEnabled(false);
        add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 210, 30));

        txtProdFeature1.setColumns(20);
        txtProdFeature1.setRows(5);
        txtProdFeature1.setEnabled(false);
        jScrollPane2.setViewportView(txtProdFeature1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 210, 55));

        jLabel10.setText("Ceil Price:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 130, 33));

        jLabel9.setText("Floor Price:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 128, 33));

        txtCeilPrice.setEnabled(false);
        add(txtCeilPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 210, 33));

        txtFloorPrice.setEnabled(false);
        add(txtFloorPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 210, 33));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(!validateEmpty())
        {
            updateDetails();
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    
    public boolean validateEmpty()
    {
      String firstName= txtProdName.getText();
        //System.out.println(firstName);
        if(firstName.trim().isEmpty()
                ||(txtProdDesc.getText().trim().isEmpty())
                ||(txtVendorName.getText().trim().isEmpty())
                ||(txtModelNumber.getText().trim().isEmpty())
                ||(txtPrice.getText().trim().isEmpty())
                ||(txtProdFeature1.getText().trim().isEmpty())
                ||(txtCeilPrice.getText().trim().isEmpty())
                ||(txtFloorPrice.getText().trim().isEmpty()))
               
               // ||JYear.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Fields cannot be blank");
          return true;
        }
        else
        {
            
            return false;
        }   
    }
    private void updateDetails() {
        
        product.setProdName(txtProdName.getText());
       if(Double.parseDouble(txtPrice.getText())<Double.parseDouble(txtFloorPrice.getText()) 
               || Double.parseDouble(txtPrice.getText())>Double.parseDouble(txtCeilPrice.getText()))
       {
       JOptionPane.showMessageDialog(null,"Please enter valid price of product between ceil and floor price range!");
           txtPrice.setText("");
       }else{
       product.setBasePrice(Double.parseDouble(txtPrice.getText()));
       }
        
        product.setModelNumber(txtModelNumber.getText());
        product.setProdDesc(txtProdDesc.getText());
        product.setVendorName(txtVendorName.getText());
        product.setProdFeature(txtProdFeature1.getText());
        if(Double.parseDouble(txtCeilPrice.getText())<Double.parseDouble(txtFloorPrice.getText())
                ||Double.parseDouble(txtCeilPrice.getText())<Double.parseDouble(txtPrice.getText()))
        {
           JOptionPane.showMessageDialog(null,"Please enter valid price!");
           txtCeilPrice.setText(""); 
        }else
        {
           product.setCeilPrice(Double.parseDouble(txtCeilPrice.getText())); 
        }
        if(Double.parseDouble(txtFloorPrice.getText())>Double.parseDouble(txtCeilPrice.getText())
                ||Double.parseDouble(txtFloorPrice.getText())>Double.parseDouble(txtPrice.getText()))
        {
            JOptionPane.showMessageDialog(null,"Please enter valid price!");
           txtFloorPrice.setText(""); 
        }else
        {
          product.setFloorPrice(Double.parseDouble(txtFloorPrice.getText()));  
        }
        
        btnSave.setEnabled(false);
        btnUpdateProduct.setEnabled(true);
        JOptionPane.showMessageDialog(null,"Product Details updated succefully!");
        
         
        clear();  
       
        
    }
    public void clear()
    {
        txtProdName.setText("");
        txtProdDesc.setText("");
        txtModelNumber.setText("");
        txtVendorName.setText("");
        txtPrice.setText("");
        txtProdFeature1.setText("");
        txtType.setText("");
        txtCeilPrice.setText("");
        txtFloorPrice.setText("");
    }
    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageProductJPanel manageProd = (ManageProductJPanel)component;
        manageProd.populateTable();       
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        // TODO add your handling code here:
        txtProdName.setEnabled(true);
        txtProdDesc.setEnabled(true);
        txtModelNumber.setEnabled(true);
        txtPrice.setEnabled(true);
        txtCeilPrice.setEnabled(true);
        txtFloorPrice.setEnabled(true);       
        txtProdFeature1.setEnabled(true);
        txtVendorName.setEnabled(true);        
        btnSave.setEnabled(true);
        btnUpdateProduct.setEnabled(false);
    }//GEN-LAST:event_btnUpdateProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCeilPrice;
    private javax.swing.JTextField txtFloorPrice;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProdDesc;
    private javax.swing.JTextArea txtProdFeature1;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtVendorName;
    // End of variables declaration//GEN-END:variables
}
