/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.hiringManager;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Neurologist.NeurologistList;
import Business.Organization.CareGiverOrganization;
import Business.Organization.ChiefNursePractitionerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.patientFamilyRole.MonitorHealthJPanel;

/**
 *
 * @author varsha
 */
public class ChiefNursePractitionerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChiefNursePractitionerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private ChiefNursePractitionerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private NeurologistList neuroList;
    public ChiefNursePractitionerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ChiefNursePractitionerOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        neuroList = new NeurologistList();
        chiefNurseNameJLabel.setText(account.getEmployee().getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        recruitNursesJButton = new javax.swing.JButton();
        chiefNurseNameJLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Welcome");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 46, 72, 24));

        recruitNursesJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        recruitNursesJButton.setText("Recruit Nurses");
        recruitNursesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recruitNursesJButtonActionPerformed(evt);
            }
        });
        add(recruitNursesJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 136, 163, 40));

        chiefNurseNameJLabel.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        add(chiefNurseNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 46, 246, 24));

        jButton1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jButton1.setText("Recruit Neurologists");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 205, 163, 41));
    }// </editor-fold>//GEN-END:initComponents

    private void recruitNursesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recruitNursesJButtonActionPerformed
        // TODO add your handling code here:
       RecruitNursesJPanel rnjp = new RecruitNursesJPanel(userProcessContainer, business, userAccount);
        userProcessContainer.add("RecruitNursesJPanel",rnjp);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_recruitNursesJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NewNeurologistsJPanel nnjp = new NewNeurologistsJPanel(userProcessContainer, business,organization, neuroList);
        userProcessContainer.add("NewNeurologistsJPanel",nnjp);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chiefNurseNameJLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton recruitNursesJButton;
    // End of variables declaration//GEN-END:variables
}
