/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.patientFamilyRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CareGiverOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientFamilyOrganization;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.PatientFamily.PatientFamily;
import Business.State.State;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ContactCareGiver;
import Business.city.City;
import java.awt.CardLayout;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpression;
import javax.xml.xpath.XPathFactory;
import org.w3c.dom.Document;

/**
 *
 * @author varsha
 */
public class TrackLocationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrackLocationJPanel
     */
    private JPanel userProcessContainer;
    private Double distance;
    private UserAccount account;
    private PatientFamilyOrganization organization;
    private EcoSystem system;
    public TrackLocationJPanel(JPanel userProcessContainer, String name, Double distance, UserAccount account, PatientFamilyOrganization organization, EcoSystem system) {
        initComponents();
       this.userProcessContainer = userProcessContainer; 
       this.distance = distance;
       this.account = account;
       this.system = system;
       this.organization = organization;
       destinationJTextField.setText(name);
       distanceJLabel.setText(String.valueOf(distance));
       if(distance > 2.0)
        {
            contactCareTakerJButton.setEnabled(true);
           // sendMailJButton.setEnabled(true);
        }
       Patient  patient = null;
       for(State state : system.getStateList())
        {
            for(City city : state.getCityList())
            {
                for(Enterprise enterprise : city.getEnterprizeDirectory().getEnterprizeList())
                {
                    for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
                    {
                        for (PatientFamily pf : org.getPatientFamilyDirectory().getPatientFamilyList())
                        {
                            if(pf.getMemberName().equalsIgnoreCase(account.getEmployee().getName()))
                            {
                                patient  = pf.getPatient();
                            }
                        }
                    }
                    
                }
            }
        }
                   
        patientNameJLabel.setText(patient.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destinationJTextField = new javax.swing.JTextField();
        patientNameJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        distanceJLabel = new javax.swing.JLabel();
        contactCareTakerJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        destinationJTextField.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        destinationJTextField.setEnabled(false);
        add(destinationJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 114, 138, -1));

        patientNameJLabel.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        add(patientNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 114, 127, 23));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("is currently at:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 114, 87, 23));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Distance from the source is: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 155, -1, 24));

        distanceJLabel.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        add(distanceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 155, 150, 24));

        contactCareTakerJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        contactCareTakerJButton.setText("Contact CareTaker");
        contactCareTakerJButton.setEnabled(false);
        contactCareTakerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactCareTakerJButtonActionPerformed(evt);
            }
        });
        add(contactCareTakerJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 273, 170, 40));

        backJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 19, 90, 30));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setText("Message for Caregiver:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 197, 170, 30));

        messageJTextField.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 198, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void contactCareTakerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactCareTakerJButtonActionPerformed
        // TODO add your handling code here:
        // Show message that care taker contacted successfully!
        String message = messageJTextField.getText();
        
        ContactCareGiver request = new ContactCareGiver();
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent");
        Organization org = null;
        for (State state : system.getStateList()) {
            for (City city : state.getCityList()) {
                for (Enterprise enterprise : city.getEnterprizeDirectory().getEnterprizeList()) {
                    
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                           
                            if (organization instanceof CareGiverOrganization) {
                                
                                org = organization;
                                break;
                            
                        }
                    }
                }
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Caregiver contacted successfully!");
        messageJTextField.setText(" ");
    }//GEN-LAST:event_contactCareTakerJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
    

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton contactCareTakerJButton;
    private javax.swing.JTextField destinationJTextField;
    private javax.swing.JLabel distanceJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JLabel patientNameJLabel;
    // End of variables declaration//GEN-END:variables
}
