/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.patientFamilyRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PatientFamilyOrganization;
import Business.Patient.Patient;
import Business.PatientFamily.PatientFamily;
import Business.State.State;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.city.City;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author varsha
 */
public class ViewCheckListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCheckListJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem business;
    private PatientFamilyOrganization organization;
    public ViewCheckListJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business,Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.organization = (PatientFamilyOrganization)organization;
        
        
        changeCheckBoxStatus();
    }

    public void changeCheckBoxStatus(){
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            for (State state : business.getStateList()) {
                for (City city : state.getCityList()) {
                    for (Enterprise e : city.getEnterprizeDirectory().getEnterprizeList()) {
                        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                            for (PatientFamily pf : o.getPatientFamilyDirectory().getPatientFamilyList()) {
                                for (Patient p : o.getPatientDirectory().getPatientList()) {
                                    if (pf.getPatient().getName().equalsIgnoreCase(p.getName())
                                           && pf.getMemberName().equalsIgnoreCase(account.getEmployee().getName())
                                            && pf.getPatient().getName().equalsIgnoreCase(request.getSender().getEmployee().getName())) {
                                       String message = request.toString();
                                       if(message.toLowerCase().contains("medicine"))
                                       {
                                           medicineCheckBox.setSelected(true);
                                       }
                                       if(message.toLowerCase().contains("puzzle"))
                                       {
                                           puzzleCheckBox.setSelected(true);
                                       }
                                       
                                        break;
                                    }
                                }

                            }
                        }

                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        puzzleCheckBox = new javax.swing.JCheckBox();
        medicineCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 66, 180, 29));

        backJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, 29));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        puzzleCheckBox.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        puzzleCheckBox.setText("Brain Puzzles");
        puzzleCheckBox.setEnabled(false);
        jPanel1.add(puzzleCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        medicineCheckBox.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        medicineCheckBox.setText("Medicines");
        medicineCheckBox.setEnabled(false);
        jPanel1.add(medicineCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 370, 310));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("checklist:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 84, 29));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox medicineCheckBox;
    private javax.swing.JCheckBox puzzleCheckBox;
    // End of variables declaration//GEN-END:variables
}
