/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.volunteerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.MedicalPractitionerOrganization;
import Business.Organization.Organization;
import Business.Organization.VolunteerOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Nirali Merchant
 */
public class PerformSurveyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVolunteerSurveyJPanel
     */
    private JPanel userProcessContainer;
   // private VolunteerOrganization organization;
    private Organization organization ;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public PerformSurveyJPanel(JPanel userProcessContainer,UserAccount account, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
     //   this.organization = (VolunteerOrganization) organization;
      this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        ethnicityButtonGroup = new javax.swing.ButtonGroup();
        problemWithMemoryButtonGroup = new javax.swing.ButtonGroup();
        balanceButtonGroup = new javax.swing.ButtonGroup();
        strokeButtonGroup = new javax.swing.ButtonGroup();
        sadButtonGroup = new javax.swing.ButtonGroup();
        activitiesButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        asianJRadioButton = new javax.swing.JRadioButton();
        blackJRadioButton = new javax.swing.JRadioButton();
        otherJRadioButton = new javax.swing.JRadioButton();
        hispanicJRadioButton = new javax.swing.JRadioButton();
        whiteJRadioButton = new javax.swing.JRadioButton();
        maleJRadioButton = new javax.swing.JRadioButton();
        femaleJRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        memoryYesJRadioButton = new javax.swing.JRadioButton();
        memoryNoJRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        memoryOcassionalJRadioButton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        balanceYesJRadioButton = new javax.swing.JRadioButton();
        balanceNoJRadioButton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        strokeYesJRadioButton = new javax.swing.JRadioButton();
        strokeNoJRadioButton = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        sadYesJRadioButton = new javax.swing.JRadioButton();
        sadNoJRadioButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        activitiesYesJRadioButton = new javax.swing.JRadioButton();
        activitiesNoJRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        takeTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ageJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 90, 30));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, 30));

        ethnicityButtonGroup.add(asianJRadioButton);
        asianJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        asianJRadioButton.setText("Asian");
        add(asianJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 70, -1));

        ethnicityButtonGroup.add(blackJRadioButton);
        blackJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        blackJRadioButton.setText("Black");
        add(blackJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 80, -1));

        ethnicityButtonGroup.add(otherJRadioButton);
        otherJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        otherJRadioButton.setText("Other");
        otherJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherJRadioButtonActionPerformed(evt);
            }
        });
        add(otherJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 90, -1));

        ethnicityButtonGroup.add(hispanicJRadioButton);
        hispanicJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        hispanicJRadioButton.setText("Hispanic");
        add(hispanicJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 90, -1));

        ethnicityButtonGroup.add(whiteJRadioButton);
        whiteJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        whiteJRadioButton.setText("White");
        add(whiteJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 70, -1));

        genderButtonGroup.add(maleJRadioButton);
        maleJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        maleJRadioButton.setText("Male");
        add(maleJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 70, -1));

        genderButtonGroup.add(femaleJRadioButton);
        femaleJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        femaleJRadioButton.setText("Female");
        add(femaleJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 80, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("Problem with Memory");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, 20));

        problemWithMemoryButtonGroup.add(memoryYesJRadioButton);
        memoryYesJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        memoryYesJRadioButton.setText("Yes");
        add(memoryYesJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 60, -1));

        problemWithMemoryButtonGroup.add(memoryNoJRadioButton);
        memoryNoJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        memoryNoJRadioButton.setText("No");
        add(memoryNoJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 60, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel7.setText("Age");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, 30));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel8.setText("Ethnicity");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 20));

        problemWithMemoryButtonGroup.add(memoryOcassionalJRadioButton);
        memoryOcassionalJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        memoryOcassionalJRadioButton.setText("Only Occassionally");
        add(memoryOcassionalJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 160, -1));

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel9.setText("Balance Problems");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, 30));

        balanceButtonGroup.add(balanceYesJRadioButton);
        balanceYesJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        balanceYesJRadioButton.setText("Yes");
        add(balanceYesJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 60, -1));

        balanceButtonGroup.add(balanceNoJRadioButton);
        balanceNoJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        balanceNoJRadioButton.setText("No");
        add(balanceNoJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 70, -1));

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel10.setText("Did you have a Major Stroke?");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 200, 40));

        strokeButtonGroup.add(strokeYesJRadioButton);
        strokeYesJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        strokeYesJRadioButton.setText("Yes");
        add(strokeYesJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 60, 30));

        strokeButtonGroup.add(strokeNoJRadioButton);
        strokeNoJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        strokeNoJRadioButton.setText("No");
        add(strokeNoJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 110, 30));

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel11.setText("Do you currently feel sad or depressed ?");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 250, 30));

        sadButtonGroup.add(sadYesJRadioButton);
        sadYesJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        sadYesJRadioButton.setText("Yes");
        add(sadYesJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, 30));

        sadButtonGroup.add(sadNoJRadioButton);
        sadNoJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        sadNoJRadioButton.setText("No");
        add(sadNoJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 80, 30));

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel12.setText("Difficulty doing everyday activities?");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 240, 40));

        activitiesButtonGroup.add(activitiesYesJRadioButton);
        activitiesYesJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        activitiesYesJRadioButton.setText("Yes");
        add(activitiesYesJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 50, 30));

        activitiesButtonGroup.add(activitiesNoJRadioButton);
        activitiesNoJRadioButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        activitiesNoJRadioButton.setText("No");
        add(activitiesNoJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 70, 30));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setText("Personal Details");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 40));

        takeTestJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        takeTestJButton.setText("Take SAGE test");
        takeTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeTestJButtonActionPerformed(evt);
            }
        });
        add(takeTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 220, 40));

        backJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 40));

        jLabel13.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel13.setText("Gender");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 20));
        add(ageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void otherJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherJRadioButtonActionPerformed

    private void takeTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeTestJButtonActionPerformed
       String name  = nameJTextField.getText();
      // String birthMonth = (String)dobMonthJComboBox.getSelectedItem();
       
    //   String birthDate = (String)dobDateComboBox.getSelectedItem();
    //   String birthYear = (String)dobYearJComboBox.getSelectedItem();
       String gender = "";
       String ethnicity = "";
       String isMemoryProblem = "";
       boolean isBalanceProblem = false;
       boolean isMajorStroke = false;
       boolean sadCurrentMood = false;
       boolean everyDayActivityProblem = false;
       
       
        if (genderButtonGroup.isSelected(maleJRadioButton.getModel())) {
             gender = "Male";
        } else {
             gender = "Female";
        }
        if (ethnicityButtonGroup.isSelected(asianJRadioButton.getModel())) {
            ethnicity = "Asian";
        } else if (ethnicityButtonGroup.isSelected(blackJRadioButton.getModel())) {
            ethnicity = "Black";
        } else if (ethnicityButtonGroup.isSelected(hispanicJRadioButton.getModel())) {
            ethnicity = "Hispanic";
        } else if (ethnicityButtonGroup.isSelected(whiteJRadioButton.getModel())) {
            ethnicity = "White";
        } else if (ethnicityButtonGroup.isSelected(otherJRadioButton.getModel())) {
            ethnicity = "Other";
        }
        if(problemWithMemoryButtonGroup.isSelected(memoryYesJRadioButton.getModel()))
        {
            isMemoryProblem = "yes";
        }
        else if(problemWithMemoryButtonGroup.isSelected(memoryNoJRadioButton.getModel()))
        {
            isMemoryProblem = "false";
        }
        else if(problemWithMemoryButtonGroup.isSelected(memoryOcassionalJRadioButton.getModel()))
        {
            isMemoryProblem = "Occassionally";
        }
        
        if(balanceButtonGroup.isSelected(balanceYesJRadioButton.getModel()))
        {
                   isBalanceProblem = true;

        }
        else if(balanceButtonGroup.isSelected(balanceYesJRadioButton.getModel()))
        {
            isBalanceProblem = false;
        }
        
        if(strokeButtonGroup.isSelected(strokeYesJRadioButton.getModel()))
        {
            isMajorStroke = true;
        }
        else if(strokeButtonGroup.isSelected(strokeNoJRadioButton.getModel()))
        {
            isMajorStroke = false;
        }
        if(sadButtonGroup.isSelected(sadYesJRadioButton.getModel()))
        
        {
            sadCurrentMood = true;
        }
        else if(sadButtonGroup.isSelected(sadNoJRadioButton.getModel()))
        {
            sadCurrentMood = false;
        }
        
        if(activitiesButtonGroup.isSelected(activitiesYesJRadioButton.getModel()))
        {
            everyDayActivityProblem = true;
        }
        else if(activitiesButtonGroup.isSelected(activitiesNoJRadioButton.getModel()))
        {
            everyDayActivityProblem = false;
        }
        
        Patient patient = organization.getPatientDirectory().addPatient();
    
        
        
      //  Patient patient = new Patient();
        patient.setName(name);
        patient.setDateRegistered(generateDate());
    //    patient.setBirthYear(birthYear);
   //     patient.setBirthMonth(birthMonth);
  //      patient.setBirthDate(birthDate);
        patient.setGender(gender);
        patient.setEthnicity(ethnicity);
        patient.setMemoryProblem(isMemoryProblem);
        patient.setBalanceProblem(isBalanceProblem);
        patient.setMajorStroke(isMajorStroke);
        patient.setSadCurrentMood(sadCurrentMood);
        patient.setEverydayActivityProblem(everyDayActivityProblem);
        
        
        

//ADD TO PATIENT DIRECTORY 
        
        
        
        JOptionPane.showMessageDialog(null, "Patient record saved successfully for early diagnosis");
        
        
        test takeTestJPanel = new test(userProcessContainer, patient, userAccount,enterprise);
        userProcessContainer.add("TakeTestJPanel", takeTestJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
      /*  TakeTestJPanel takeTestJPanel = new TakeTestJPanel(userProcessContainer, patient, userAccount,enterprise);
        userProcessContainer.add("TakeTestJPanel", takeTestJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        */
        
        
        
        
            
            
    }//GEN-LAST:event_takeTestJButtonActionPerformed

    public static Date generateDate()
    {
    Date dMin = null;
    Date dMax = null;
      Calendar cal = Calendar.getInstance();
        cal.add(Calendar.YEAR, -1); // today minus one year
         dMin = cal.getTime();
        cal.add(Calendar.YEAR, 2); // today plus one year
         dMax = cal.getTime();
        long MILLIS_PER_DAY = 1000*60*60*24;
        GregorianCalendar s = new GregorianCalendar();
        s.setTimeInMillis(dMin.getTime());
        GregorianCalendar e = new GregorianCalendar();
        e.setTimeInMillis(dMax.getTime());
        
        // Get difference in milliseconds
        long endL   =  e.getTimeInMillis() +  e.getTimeZone().getOffset(e.getTimeInMillis());
        long startL = s.getTimeInMillis() + s.getTimeZone().getOffset(s.getTimeInMillis());
        long dayDiff = (endL - startL) / MILLIS_PER_DAY;
        
        
        cal.setTime(dMin);
        cal.add(Calendar.DATE, new Random().nextInt((int)dayDiff));          
        return cal.getTime();
   
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup activitiesButtonGroup;
    private javax.swing.JRadioButton activitiesNoJRadioButton;
    private javax.swing.JRadioButton activitiesYesJRadioButton;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JRadioButton asianJRadioButton;
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup balanceButtonGroup;
    private javax.swing.JRadioButton balanceNoJRadioButton;
    private javax.swing.JRadioButton balanceYesJRadioButton;
    private javax.swing.JRadioButton blackJRadioButton;
    private javax.swing.ButtonGroup ethnicityButtonGroup;
    private javax.swing.JRadioButton femaleJRadioButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JRadioButton hispanicJRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton maleJRadioButton;
    private javax.swing.JRadioButton memoryNoJRadioButton;
    private javax.swing.JRadioButton memoryOcassionalJRadioButton;
    private javax.swing.JRadioButton memoryYesJRadioButton;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JRadioButton otherJRadioButton;
    private javax.swing.ButtonGroup problemWithMemoryButtonGroup;
    private javax.swing.ButtonGroup sadButtonGroup;
    private javax.swing.JRadioButton sadNoJRadioButton;
    private javax.swing.JRadioButton sadYesJRadioButton;
    private javax.swing.ButtonGroup strokeButtonGroup;
    private javax.swing.JRadioButton strokeNoJRadioButton;
    private javax.swing.JRadioButton strokeYesJRadioButton;
    private javax.swing.JButton takeTestJButton;
    private javax.swing.JRadioButton whiteJRadioButton;
    // End of variables declaration//GEN-END:variables
}
