/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.volunteerRole;

import Business.Caregiver.Caregiver;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import Business.PatientFamily.PatientFamily;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Nirali Merchant
 */
public class RegisterActivePatientsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterActivePatientsJPanel
     */
    private JPanel userProcessContainer;
    private String patient;
    private Organization organization;
    public RegisterActivePatientsJPanel(JPanel userProcessContainer, String patient , Organization organization)
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.organization = organization;
        firstNameJLabel.setText(patient);
       // ageJLabel.
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        firstNameJLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ageJLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressLine1TextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pinCodeJTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        contactNumberJTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Relationship = new javax.swing.JLabel();
        Relationship2 = new javax.swing.JLabel();
        registerJButton = new javax.swing.JButton();
        family1NameJTextField = new javax.swing.JTextField();
        familycontact1JTextField = new javax.swing.JTextField();
        familyrelationship1JTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        caregiverNameJTextFeild = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        firstNameJtextField = new javax.swing.JLabel();
        ageJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("Patient Family Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 192, 30));
        add(firstNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 220, 30));

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel9.setText("Age");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, 25));

        ageJLabel.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        add(ageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 50, 90, 47));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 166, -1, -1));

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel12.setText("Address Line 1");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 100, 31));

        addressLine1TextArea.setColumns(20);
        addressLine1TextArea.setRows(5);
        jScrollPane1.setViewportView(addressLine1TextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 221, 70));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setText("City");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 80, 30));

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel5.setText("State");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, 27));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel8.setText("Pin Code");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 100, 28));
        add(pinCodeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 221, 35));

        jLabel13.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel13.setText("Contact Number");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, 30));

        contactNumberJTextField.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        add(contactNumberJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 221, 36));

        jLabel15.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel15.setText("Patient Details");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 160, 40));

        jLabel16.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel16.setText("Name");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 90, 34));

        Relationship.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        Relationship.setText("Relationship");
        add(Relationship, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 80, 30));

        Relationship2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        Relationship2.setText("Contact Number");
        add(Relationship2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 110, 30));

        registerJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        registerJButton.setText("Register");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });
        add(registerJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 810, 220, 40));
        add(family1NameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 225, 34));
        add(familycontact1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 225, 30));
        add(familyrelationship1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 225, 30));

        jLabel20.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel20.setText("Caregiver Details");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 720, -1, 29));

        jLabel21.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel21.setText("Name");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 760, 70, 33));

        caregiverNameJTextFeild.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        add(caregiverNameJTextFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 760, 225, 33));

        backJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 110, 40));
        add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 221, 39));
        add(stateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 221, 36));
        add(firstNameJtextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 182, 30));
        add(ageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        // TODO add your handling code here:
        
        String addressLine1 = addressLine1TextArea.getText();

        boolean isUniquePatient = true;
        boolean added = true;
        String city = cityTextField.getText();
        String state = stateTextField.getText();
        int pinCode = 0;
        int age = Integer.parseInt(ageJTextField.getText());
        int contactNumber = 0;
        try {
            pinCode = Integer.parseInt(pinCodeJTextField.getText());
            contactNumber = Integer.parseInt(contactNumberJTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter valid Data");
        }
        String caregiverName = caregiverNameJTextFeild.getText();
        //  for (Patient p : organization.getPatientFamilyDirectory().getPatientFamilyList())

        if (addressLine1.trim().isEmpty() || city.trim().isEmpty() || state.trim().isEmpty()
                || caregiverName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All the fields should be filled");
        } else {
            Caregiver cg = null;
            for (Caregiver caregiver : organization.getCgList().getCaregiverList()) {
                if (caregiver.getCareGiverName().equalsIgnoreCase(caregiverNameJTextFeild.getText())) {
                    //caregiver.setCareGiverName(patient);
                    cg = caregiver;
                }
            }

            for (Patient activePatient : organization.getPatientDirectory().getPatientList()) {
               // isUniquePatient = organization.getPatientDirectory().checkIfPatientIsUnique(organization, patient);
                //if (isUniquePatient) {
                    if (activePatient.getName().equals(patient)) {
                        //activePatient.setName(patient);
                        activePatient.setCity(city);
                        activePatient.setAddressline1(addressLine1);
                        activePatient.setPincode(pinCode);
                        activePatient.setCareGiver(cg);

                        for (PatientFamily pf : organization.getPatientFamilyDirectory().getPatientFamilyList()) {
                            if (pf.getMemberName().equalsIgnoreCase(family1NameJTextField.getText())) {
                                pf.setRelaionship(familyrelationship1JTextField.getText());
                                pf.setContact((Integer.parseInt(familycontact1JTextField.getText())));
                                break;
                            }

                            pf.setPatient(activePatient);

                        }

                    }
                   // added = true;
                   // break;
                } //else {
                  //  added = false;
                   // break;
                //}
           // }
            JOptionPane.showMessageDialog(null, "Patient Registered successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
           addressLine1TextArea.setText(" ");
           cityTextField.setText(" ");
           stateTextField.setText(" ");
           pinCodeJTextField.setText(" ");
           contactNumberJTextField.setText(" ");
           caregiverNameJTextFeild.setText(" ");
           family1NameJTextField.setText(" ");
           familyrelationship1JTextField.setText(" ");
           contactNumberJTextField.setText(" ");
        }
    }//GEN-LAST:event_registerJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Relationship;
    private javax.swing.JLabel Relationship2;
    private javax.swing.JTextArea addressLine1TextArea;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField caregiverNameJTextFeild;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField contactNumberJTextField;
    private javax.swing.JTextField family1NameJTextField;
    private javax.swing.JTextField familycontact1JTextField;
    private javax.swing.JTextField familyrelationship1JTextField;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JLabel firstNameJtextField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pinCodeJTextField;
    private javax.swing.JButton registerJButton;
    private javax.swing.JTextField stateTextField;
    // End of variables declaration//GEN-END:variables
}
