/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.volunteerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.MedicalPractitionerOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.Patient;
import Business.Organization.ResearcherOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ResearchAnalysisWorkRequest;
import Business.WorkQueue.VolunteerMedicalPracWorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Nirali Merchant
 */
public class TakeTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TakeTestJPanel
     */
    private JPanel userProcessContainer;
    private Patient patient;
    private UserAccount userAccount;
    private Enterprise enterprise;

    TakeTestJPanel(JPanel userProcessContainer, Patient patient, UserAccount userAccount, Enterprise enterprise) {
       this.userProcessContainer = userProcessContainer;
       this.patient = patient;
       this.userAccount = userAccount;
       this.enterprise = enterprise;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dateJTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        answer2aJTextField = new javax.swing.JTextField();
        answer2bJTextField = new javax.swing.JTextField();
        answer3JTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Submit.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 140, 30));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("How well are you Thinking?");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 210, 40));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("Please complete this form without assistance of others");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setText("1. What is today's date ?");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 153, 30));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setText("2. Name the following picture");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 300, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/volunteerRole/Tree.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 80, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/volunteerRole/christmasRing.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, 100));

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel10.setText("3. How many cents are in 4$ ?");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 180, 30));
        add(dateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 150, 30));

        jButton1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));
        add(answer2aJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 80, 30));
        add(answer2bJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 90, 30));
        add(answer3JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 140, 30));

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel6.setText("MM-DD-YYYY");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
      
      
      Date date = null;
      int testScore = 0;
      String todaysDate = dateJTextField.getText();
      String answer2a = answer2aJTextField.getText();
      String answer2b = answer2bJTextField.getText();
      int answer3 = Integer.parseInt(answer3JTextField.getText());
      
      DateFormat formatter = new SimpleDateFormat("MM/DD/YYYY");
      try
      {
       date = (Date)formatter.parse(todaysDate);
      }
      catch(Exception e)
      {
          
      }
      Date systemDate = new Date();
      //validation for empty text fields
      if((dateJTextField.getText().trim().isEmpty()) || (answer2aJTextField.getText().trim().isEmpty())
              || (answer2bJTextField.getText().trim().isEmpty()))
      {
          JOptionPane.showMessageDialog(null, "Please answer all the questions");
      }
        
      if(systemDate.equals(date))
      {
          ++testScore;
      }
      if(answer2a.equalsIgnoreCase("Tree"))
      {
          ++testScore;
      }
      if(answer2b.equalsIgnoreCase("Christmas Band"))
      {
          ++testScore;
      }
      if(answer3 == 400)
      {
          ++testScore;
                  
      }
      
      patient.setSageTestScore(testScore);
      
      
      if(testScore <= 2)
      {
          patient.setEarlyAlzhimers(true);
          
          
         VolunteerMedicalPracWorkRequest request = new VolunteerMedicalPracWorkRequest();
         request.setMessage("FurtherAnalysis");
         request.setSender(userAccount);
        
         request.setStatus("Sent");

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof MedicalPractitionerOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null,"Request successfully submitted", "Information", JOptionPane.INFORMATION_MESSAGE);
        }

    }                                                    

      
      else
      {
          patient.setEarlyAlzhimers(false);
      }
      dateJTextField.setText(" ");
      answer2aJTextField.setText(" ");
      answer2bJTextField.setText(" ");
      answer3JTextField.setText(" ");
      
     
    }//GEN-LAST:event_SubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JTextField answer2aJTextField;
    private javax.swing.JTextField answer2bJTextField;
    private javax.swing.JTextField answer3JTextField;
    private javax.swing.JTextField dateJTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
