/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.caregiver;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CareGiverOrganization;
import Business.Organization.MedicalPractitionerOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.State.State;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CaregiverToMedicalPractitioner;
import Business.WorkQueue.GroupChatCommunication;
import Business.WorkQueue.WorkRequest;
import Business.city.City;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nirali Merchant
 */
public class AssociationHelplineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssociationHelplineJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private CareGiverOrganization organization;
    private EcoSystem business;
    public AssociationHelplineJPanel(JPanel userProcessContainer,UserAccount account, Enterprise enterprise, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.enterprise = enterprise;
        this.organization = (CareGiverOrganization)organization;
        populateTable();
    }

    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) cgToMpJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest req : organization.getWorkQueue().getWorkRequestList()) {
            if((req.getSender().getRole().toString().equals("CareGiver Role"))
                    || req.getSender().getRole().toString().equals("MedicalPractitioner Role")
                    ){
            Object[] row = new Object[2];
            row[0] = req.getMessage();
           //row[1] = req.getSender();
            String result = ((CaregiverToMedicalPractitioner) req).getTestResult();
             row[1] = result == null ? "Waiting" : result;
            model.addRow(row);
        }
        }
       // model.setRowCount(0);
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {

          
            Object[] row = new Object[3];
            row[0] = request.getMessage();

            row[1] = request.getSender();
            
             String result = ((CaregiverToMedicalPractitioner) request).getTestResult();
             row[2] = result == null ? "Waiting" : result;
            model.addRow(row);
            break;
           
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        textJTextField = new javax.swing.JTextField();
        consultJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cgToMpJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Chat Live with our Medical Practitioner");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 103, 250, 27));

        backJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 21, 82, 36));
        add(textJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 148, 207, 33));

        consultJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        consultJButton.setText("Consult Medical Practitioner");
        consultJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultJButtonActionPerformed(evt);
            }
        });
        add(consultJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 148, -1, 33));

        cgToMpJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Reply"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cgToMpJTable);
        if (cgToMpJTable.getColumnModel().getColumnCount() > 0) {
            cgToMpJTable.getColumnModel().getColumn(0).setResizable(false);
            cgToMpJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 267, 448, 183));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel2.setText("Chat Window!");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 213, 207, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void consultJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultJButtonActionPerformed
        // TODO add your handling code here:
        String message = textJTextField.getText();
        CaregiverToMedicalPractitioner request = new CaregiverToMedicalPractitioner();
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent");

        Organization org = null;

        for (State state : business.getStateList()) {
            for (City city : state.getCityList()) {
                for (Enterprise enterprise : city.getEnterprizeDirectory().getEnterprizeList()) {

                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof MedicalPractitionerOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
        }
    
        

        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null,"Your message has reached a representative of the association! Expect reply shortly");
        textJTextField.setText(" ");
    }//GEN-LAST:event_consultJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable cgToMpJTable;
    private javax.swing.JButton consultJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textJTextField;
    // End of variables declaration//GEN-END:variables
}
