/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.caregiver;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CareGiverOrganization;
import Business.Role.PatientRole;
import Business.Schedule.Task;
import Business.Schedule.TaskList;
import Business.UserAccount.UserAccount;
import Business.VitalSign.VitalSignHistory;
import java.awt.CardLayout;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Random;
import javax.swing.JPanel;

/**
 *
 * @author Nirali Merchant
 */
public class CaregiverWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CaregiverWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private CareGiverOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private VitalSignHistory vsh;
     public static Date dMin = null;
    public static Date dMax = null;
    private TaskList taskList;
    private EcoSystem system;
    //private PatientRole patient;
    public CaregiverWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CareGiverOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        vsh = new VitalSignHistory();
        taskList = new TaskList();
        careGiverNameJLabel.setText(account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caregiverCenterJButton = new javax.swing.JButton();
        addVitalSignsJButton = new javax.swing.JButton();
        viewMyTasksJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        careGiverNameJLabel = new javax.swing.JLabel();
        updateScheduleJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caregiverCenterJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        caregiverCenterJButton.setText("Caregiver Center");
        caregiverCenterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caregiverCenterJButtonActionPerformed(evt);
            }
        });
        add(caregiverCenterJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 163, 263, 38));

        addVitalSignsJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        addVitalSignsJButton.setText("Add Vital Signs");
        addVitalSignsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVitalSignsJButtonActionPerformed(evt);
            }
        });
        add(addVitalSignsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 219, 263, 40));

        viewMyTasksJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        viewMyTasksJButton.setText("View my Messages");
        viewMyTasksJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMyTasksJButtonActionPerformed(evt);
            }
        });
        add(viewMyTasksJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, 263, 43));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Welcome");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, 84, 29));

        careGiverNameJLabel.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        careGiverNameJLabel.setText("jLabel2");
        add(careGiverNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 32, 274, 29));

        updateScheduleJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        updateScheduleJButton.setText("Update Patient's Schedule");
        updateScheduleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateScheduleJButtonActionPerformed(evt);
            }
        });
        add(updateScheduleJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 277, 263, 44));
    }// </editor-fold>//GEN-END:initComponents

    private void caregiverCenterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caregiverCenterJButtonActionPerformed
        // TODO add your handling code here:
        CaregiverCenterJPanel cgcjp = new CaregiverCenterJPanel(userProcessContainer, userAccount, enterprise, organization, system);
        userProcessContainer.add("CaregiverCenterJPanel",cgcjp);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_caregiverCenterJButtonActionPerformed

    private void addVitalSignsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVitalSignsJButtonActionPerformed
        // TODO add your handling code here:
      /* ManageVitalSignsJPanel mvsjp = new ManageVitalSignsJPanel(userProcessContainer,vsh, userAccount, system);
        userProcessContainer.add("ManageVitalSignsJPanel",mvsjp);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer); */
      ManageVitalSignsJPanel mvsjp = new ManageVitalSignsJPanel(userProcessContainer,vsh, userAccount, system);
        userProcessContainer.add("ManageVitalSignsJPanel",mvsjp);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addVitalSignsJButtonActionPerformed

    private void viewMyTasksJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMyTasksJButtonActionPerformed
        // TODO add your handling code here:
        ManageCaregiverTasksJPanel mctjp = new ManageCaregiverTasksJPanel(userProcessContainer, userAccount, organization, enterprise, system);
        userProcessContainer.add("ManageCaregiverTasksJPanel",mctjp);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewMyTasksJButtonActionPerformed

    private void updateScheduleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateScheduleJButtonActionPerformed
        // TODO add your handling code here:
       PatientsTaskListJPanel ptljp = new PatientsTaskListJPanel(userProcessContainer, userAccount, taskList, enterprise, system);
        userProcessContainer.add("PatientsTaskListJPanel",ptljp);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
        
    }//GEN-LAST:event_updateScheduleJButtonActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVitalSignsJButton;
    private javax.swing.JLabel careGiverNameJLabel;
    private javax.swing.JButton caregiverCenterJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updateScheduleJButton;
    private javax.swing.JButton viewMyTasksJButton;
    // End of variables declaration//GEN-END:variables
}
