/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.caregiver;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CareGiverOrganization;
import Business.Organization.MedicalPractitionerOrganization;
import Business.Organization.NeurologistOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.PatientFamily.PatientFamily;
import Business.State.State;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AddTasksForPatient;
import Business.WorkQueue.CaregiverToMedicalPractitioner;
import Business.WorkQueue.GroupChatCommunication;
import Business.WorkQueue.WorkRequest;
import Business.city.City;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nirali Merchant
 */
public class DiscussionForumJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiscussionForumJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private CareGiverOrganization organization;
    private EcoSystem business;
    public DiscussionForumJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        this.enterprise = enterprise;
        this.organization = (CareGiverOrganization)organization;
        populateTable();
    }

    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) forumJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest req : organization.getWorkQueue().getWorkRequestList()) {
            if(((req instanceof GroupChatCommunication)&&(req.getSender().getRole().toString().equals("CareGiver Role")))
                    
                    || ((req instanceof GroupChatCommunication)&&(req.getSender().getRole().toString().equals("Neurologist Role")))){
            Object[] row = new Object[3];
            row[0] = req.getMessage();
            row[1] = req.getSender();
            String result = ((GroupChatCommunication) req).getTestResult();
             row[2] = result == null ? "Waiting" : result;
            model.addRow(row);
        }
        }
       // model.setRowCount(0);
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {

          if(request instanceof GroupChatCommunication){
            Object[] row = new Object[3];
            row[0] = request.getMessage();

            row[1] = request.getSender();
            
                String result = ((GroupChatCommunication) request).getTestResult();
                row[2] = result == null ? "Waiting" : result;
            
            //String result = ((GroupChatCommunication) request).getTestResult();
            
           // row[2] = "test";
            model.addRow(row);
            break;
           
            
        }
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        commentJTextField = new javax.swing.JTextField();
        postJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        forumJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Chat Live with Caregivers and Neurologists");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 114, 340, 30));

        backJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 20, 80, 30));
        add(commentJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 376, 240, 40));

        postJButton.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        postJButton.setText("Post Comment");
        postJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postJButtonActionPerformed(evt);
            }
        });
        add(postJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 376, 227, 40));

        forumJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Reply"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(forumJTable);
        if (forumJTable.getColumnModel().getColumnCount() > 0) {
            forumJTable.getColumnModel().getColumn(1).setResizable(false);
            forumJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 162, 485, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void postJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postJButtonActionPerformed
        // TODO add your handling code here:
        //send message to other caregivers
        String message4 = commentJTextField.getText();
        GroupChatCommunication request4 = new GroupChatCommunication();
        request4.setMessage(message4);
        request4.setSender(account);
        request4.setStatus("Sent");

        Organization org = null;

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof CareGiverOrganization) {
                org = organization;
                break;
            }
        }

        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request4);
            account.getWorkQueue().getWorkRequestList().add(request4);
        }
        
        populateTable();
        
        // neurologist
        
        //GroupChatCommunication req = new GroupChatCommunication();
       // req.setMessage(message4);
       // req.setSender(account);
       // req.setStatus("Sent");
        Organization org1 = null;

       for (State state : business.getStateList()) {
            for (City city : state.getCityList()) {
                for (Enterprise enterprise : city.getEnterprizeDirectory().getEnterprizeList()) {
                    
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if (organization instanceof NeurologistOrganization) {
                                org1 = organization;
                                break;
                            
                        }
                    }
                }
            }
        }
       

        if (org1 != null) {
            org1.getWorkQueue().getWorkRequestList().add(request4);
            account.getWorkQueue().getWorkRequestList().add(request4);
        }

        JOptionPane.showMessageDialog(null,"Comment Posted on forum!!");
        commentJTextField.setText(" ");
    }//GEN-LAST:event_postJButtonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField commentJTextField;
    private javax.swing.JTable forumJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton postJButton;
    // End of variables declaration//GEN-END:variables
}
