/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resumebuildergui;


import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;

import resumebuilder.Resume;
import resumebuilder.ResumeCollection;

/**
 *
 * @author varsha
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private ResumeCollection resume;
    //private Education degree1;
    //private Education degree2;
    private String path;
    private int zc;
    private int year1;
    private int year2;
    private Double cgp1;
    private Double cgp2;
    private Long contact;
    //private Resume  res;
    public CreateJPanel(ResumeCollection resume) {
        initComponents();
        this.resume = resume;
        //this.degree1=degree1;
       // this.degree2=degree2;
       // zc=0;
        //year1=0;
        //cgp1=0.0;
        cgp2=0.0;
         //contact=0;  
         year2=0;
        othersTextField.setVisible(false);        
        jScrollPane2.setBorder(null);
        //firstRadioButtonMale.setSelected(true);
       // firstRadioButtonUS.setSelected(true);
        //firstRadioButtonGraduate.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator20 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        JUnivNameLabel = new javax.swing.JLabel();
        JyearLabel = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        JCgpa = new javax.swing.JTextField();
        JYear = new javax.swing.JTextField();
        JUnivName = new javax.swing.JTextField();
        JDegree1Name = new javax.swing.JTextField();
        JDegree1Name1 = new javax.swing.JTextField();
        JUnivName1 = new javax.swing.JTextField();
        JYear1 = new javax.swing.JTextField();
        JCgpa1 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JFirstNameLabel = new javax.swing.JLabel();
        JFirstNameTextField = new javax.swing.JTextField();
        JLastName = new javax.swing.JLabel();
        JLastNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JAddressLine2 = new javax.swing.JLabel();
        JAddressLineTextField = new javax.swing.JTextField();
        JImage = new javax.swing.JLabel();
        JBrowse = new javax.swing.JButton();
        JAddressLine4 = new javax.swing.JLabel();
        JAddressLine2TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JCityTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JStateTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JZipCodeTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailidTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contactTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JCareerObjectiveField = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        experienceTextField = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        degreenameTextField1 = new javax.swing.JTextField();
        degreenameTextField2 = new javax.swing.JTextField();
        degreeuniTextField2 = new javax.swing.JTextField();
        degreeyearTextField1 = new javax.swing.JTextField();
        degreeyearTextField2 = new javax.swing.JTextField();
        degreecgpaTextField2 = new javax.swing.JTextField();
        degreeuniTextField1 = new javax.swing.JTextField();
        degreecgpaTextField1 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        projTextField = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        checkBoxJava = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        checkBoxC = new javax.swing.JCheckBox();
        checkBoxHtml = new javax.swing.JCheckBox();
        checkBoxCss = new javax.swing.JCheckBox();
        checkBoxPhp = new javax.swing.JCheckBox();
        checkBoxSql = new javax.swing.JCheckBox();
        checkBoxPlsql = new javax.swing.JCheckBox();
        checkBoxCsharp = new javax.swing.JCheckBox();
        checkBoxOthers = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        awardsTextField = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        certificationTextField = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        partiipateTextField = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        countryTextField = new javax.swing.JTextField();
        firstRadioButtonMale = new javax.swing.JRadioButton();
        firstRadioButtonFemale = new javax.swing.JRadioButton();
        firstRadioButtonUS = new javax.swing.JRadioButton();
        firstRadioButtonInternational = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        firstRadioButtonGraduate = new javax.swing.JRadioButton();
        firstRadioButtonUndergrad = new javax.swing.JRadioButton();
        createButton = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        affiliationTextField = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        othersTextField = new javax.swing.JTextArea();

        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel14.setText("Degree2 ");

        jLabel15.setText("Degree1 ");

        jLabel16.setText("Degree Name");

        JUnivNameLabel.setText("University Name");

        JyearLabel.setText("Year of Passing");

        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);

        JYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JYearActionPerformed(evt);
            }
        });

        JUnivName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUnivNameActionPerformed(evt);
            }
        });

        JDegree1Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDegree1Name1ActionPerformed(evt);
            }
        });

        JCgpa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCgpa1ActionPerformed(evt);
            }
        });

        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("RESUME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 11, 99, 27));

        JFirstNameLabel.setText("First Name:");
        jPanel1.add(JFirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 30));

        JFirstNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JFirstNameTextField.setNextFocusableComponent(JAddressLine2);
        JFirstNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JFirstNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JFirstNameTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(JFirstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, 30));

        JLastName.setText("Last Name:");
        jPanel1.add(JLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 30));

        JLastNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JLastNameTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(JLastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 140, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel1.setText("Address");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, 30));

        JAddressLine2.setText("Address Line 1:");
        jPanel1.add(JAddressLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 23));
        jPanel1.add(JAddressLineTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 140, 30));
        jPanel1.add(JImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 30, 170, 160));

        JBrowse.setBackground(new java.awt.Color(204, 204, 204));
        JBrowse.setText("Upload Image");
        JBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBrowseActionPerformed(evt);
            }
        });
        jPanel1.add(JBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        JAddressLine4.setText("Address Line 2:");
        jPanel1.add(JAddressLine4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 90, 26));
        jPanel1.add(JAddressLine2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 140, 30));

        jLabel7.setText("City");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 70, 30));

        JCityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JCityTextFieldFocusLost(evt);
            }
        });
        JCityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCityTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(JCityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 140, 30));

        jLabel3.setText("State");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 100, 30));

        JStateTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JStateTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(JStateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 140, 30));

        jLabel4.setText("Country");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 90, 30));

        jLabel6.setText("Zip Code");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 80, 23));

        JZipCodeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JZipCodeTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(JZipCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 140, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 640, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 640, 10));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 584, 121, 26));

        jLabel8.setText("Gender:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, 30));

        emailidTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailidTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(emailidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, 30));

        jLabel9.setText("Email ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 30));

        jLabel10.setText("Contact:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 30));

        contactTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactTextFieldFocusLost(evt);
            }
        });
        contactTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactTextFieldMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                contactTextFieldMouseReleased(evt);
            }
        });
        jPanel1.add(contactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, 30));

        jLabel11.setText("Career Objective");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 100, 30));

        JCareerObjectiveField.setColumns(20);
        JCareerObjectiveField.setRows(5);
        jScrollPane3.setViewportView(JCareerObjectiveField);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 260, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1070, 630, 10));

        jLabel22.setText("Experience");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 830, 80, 23));

        experienceTextField.setColumns(20);
        experienceTextField.setRows(5);
        jScrollPane5.setViewportView(experienceTextField);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 860, 260, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1240, 640, 10));

        jLabel12.setText("Academics");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1080, 93, 22));

        jLabel13.setText("Education");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1150, -1, 23));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 820, 870, 10));

        jLabel17.setText("Degree 1");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1260, 70, 27));

        jLabel18.setText("Degree 2");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1320, 70, 29));

        jLabel19.setText("Degree Name");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1209, 91, 20));

        jLabel20.setText("University");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1210, 89, 20));

        jLabel21.setText("Year of Passing ");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1209, 110, 20));

        jLabel23.setText("CGPA");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1209, 63, 20));

        degreenameTextField1.setBackground(new java.awt.Color(204, 204, 204));
        degreenameTextField1.setBorder(null);
        degreenameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreenameTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(degreenameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1260, 86, 27));

        degreenameTextField2.setBackground(new java.awt.Color(204, 204, 204));
        degreenameTextField2.setBorder(null);
        degreenameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreenameTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(degreenameTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1310, 86, 29));

        degreeuniTextField2.setBackground(new java.awt.Color(204, 204, 204));
        degreeuniTextField2.setBorder(null);
        jPanel1.add(degreeuniTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1310, 86, 29));

        degreeyearTextField1.setBackground(new java.awt.Color(204, 204, 204));
        degreeyearTextField1.setBorder(null);
        degreeyearTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                degreeyearTextField1FocusLost(evt);
            }
        });
        jPanel1.add(degreeyearTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1260, 86, 27));

        degreeyearTextField2.setBackground(new java.awt.Color(204, 204, 204));
        degreeyearTextField2.setBorder(null);
        degreeyearTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                degreeyearTextField2FocusLost(evt);
            }
        });
        jPanel1.add(degreeyearTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1310, 86, 29));

        degreecgpaTextField2.setBackground(new java.awt.Color(204, 204, 204));
        degreecgpaTextField2.setBorder(null);
        degreecgpaTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                degreecgpaTextField2FocusLost(evt);
            }
        });
        jPanel1.add(degreecgpaTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1310, 86, 29));

        degreeuniTextField1.setBackground(new java.awt.Color(204, 204, 204));
        degreeuniTextField1.setBorder(null);
        jPanel1.add(degreeuniTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 1260, 86, 27));

        degreecgpaTextField1.setBackground(new java.awt.Color(204, 204, 204));
        degreecgpaTextField1.setBorder(null);
        degreecgpaTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                degreecgpaTextField1FocusLost(evt);
            }
        });
        jPanel1.add(degreecgpaTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 1260, 86, 27));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1160, 486, 18));

        jLabel24.setText("Projects");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1380, 98, 30));

        projTextField.setColumns(20);
        projTextField.setRows(5);
        jScrollPane4.setViewportView(projTextField);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1420, 264, 125));

        jLabel25.setText("Skills");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1570, 88, 28));

        checkBoxJava.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxJava.setText("JAVA");
        jPanel1.add(checkBoxJava, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1640, -1, -1));

        jLabel26.setText("*Select all those applicable");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1610, 168, 19));

        checkBoxC.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxC.setText("C++");
        jPanel1.add(checkBoxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1670, -1, -1));

        checkBoxHtml.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxHtml.setText("HTML");
        jPanel1.add(checkBoxHtml, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1700, -1, -1));

        checkBoxCss.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxCss.setText("CSS");
        jPanel1.add(checkBoxCss, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1640, -1, -1));

        checkBoxPhp.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxPhp.setText("PHP");
        jPanel1.add(checkBoxPhp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1670, -1, -1));

        checkBoxSql.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxSql.setText("SQL");
        jPanel1.add(checkBoxSql, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1700, -1, -1));

        checkBoxPlsql.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxPlsql.setText("PL/SQL");
        jPanel1.add(checkBoxPlsql, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1640, -1, -1));

        checkBoxCsharp.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxCsharp.setText("C#");
        jPanel1.add(checkBoxCsharp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1670, -1, -1));

        checkBoxOthers.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxOthers.setText("Others");
        checkBoxOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxOthersActionPerformed(evt);
            }
        });
        jPanel1.add(checkBoxOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1700, -1, -1));

        jLabel27.setText("Awards and Honors");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1910, 110, 31));

        awardsTextField.setColumns(20);
        awardsTextField.setRows(5);
        jScrollPane7.setViewportView(awardsTextField);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1960, 270, 130));

        jLabel28.setText("Certifications");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2100, 122, 28));

        certificationTextField.setColumns(20);
        certificationTextField.setRows(5);
        jScrollPane8.setViewportView(certificationTextField);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2146, 270, 140));

        jLabel29.setText("Participations");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2300, 105, 27));

        partiipateTextField.setColumns(20);
        partiipateTextField.setRows(5);
        jScrollPane9.setViewportView(partiipateTextField);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2346, 260, 130));

        jLabel30.setText("Nationality:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 259, 70, 21));

        countryTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(countryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 140, 27));

        firstRadioButtonMale.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(firstRadioButtonMale);
        firstRadioButtonMale.setSelected(true);
        firstRadioButtonMale.setText("Male");
        firstRadioButtonMale.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                firstRadioButtonMalePropertyChange(evt);
            }
        });
        jPanel1.add(firstRadioButtonMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 214, -1, -1));

        firstRadioButtonFemale.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup2.add(firstRadioButtonFemale);
        firstRadioButtonFemale.setText("Female");
        jPanel1.add(firstRadioButtonFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 214, 87, -1));

        firstRadioButtonUS.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup3.add(firstRadioButtonUS);
        firstRadioButtonUS.setSelected(true);
        firstRadioButtonUS.setText("US Citizen");
        jPanel1.add(firstRadioButtonUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 258, -1, -1));

        firstRadioButtonInternational.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup3.add(firstRadioButtonInternational);
        firstRadioButtonInternational.setText("International");
        jPanel1.add(firstRadioButtonInternational, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 258, -1, -1));

        jLabel31.setText("Type of Student:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1120, 97, 22));

        firstRadioButtonGraduate.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup4.add(firstRadioButtonGraduate);
        firstRadioButtonGraduate.setSelected(true);
        firstRadioButtonGraduate.setText("Graduate");
        jPanel1.add(firstRadioButtonGraduate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1120, -1, -1));

        firstRadioButtonUndergrad.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup4.add(firstRadioButtonUndergrad);
        firstRadioButtonUndergrad.setText("Undergraduate");
        jPanel1.add(firstRadioButtonUndergrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1120, -1, -1));

        createButton.setText("CREATE");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2500, 203, 46));

        jLabel32.setText("Affiliation");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 980, 120, 25));
        jPanel1.add(affiliationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1010, 260, 28));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1200, 640, 10));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1302, 640, 10));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1200, 10, 160));

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1200, 30, 160));

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1200, 10, 160));

        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1200, 10, 160));

        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1200, 10, 160));

        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1200, 10, 160));
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1362, 640, 10));

        jLabel33.setText("Projects");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1380, 98, 30));

        othersTextField.setColumns(20);
        othersTextField.setRows(5);
        othersTextField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(othersTextField);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1750, 280, 140));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 2599, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JYearActionPerformed

    private void JUnivNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUnivNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JUnivNameActionPerformed

    private void JDegree1Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDegree1Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JDegree1Name1ActionPerformed

    private void JCgpa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCgpa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCgpa1ActionPerformed

    private void JCityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCityTextFieldActionPerformed

    private void JBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBrowseActionPerformed
        // TODO add your handling code here:
        
        JFileChooser choose=new JFileChooser();
        int result= choose.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION) //if user clicks on save or open
        {
            File file= choose.getSelectedFile();
            path=file.getAbsolutePath(); //store the complete path
            //Resume rs=resume.addResume();
            
            System.out.println(path);
            //JImage.setIcon(new ImageIcon(new ImageIcon(path).getImage()));//retrive the image present at the seected path and then assign the image to Imageicon class
            ImageIcon icon= new ImageIcon(path);
            Image img=icon.getImage().getScaledInstance(170,160,Image.SCALE_SMOOTH);
            
            ImageIcon finalicon=new ImageIcon(img);
            JImage.setIcon(finalicon);
            
            }
    }//GEN-LAST:event_JBrowseActionPerformed

    private void degreenameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreenameTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreenameTextField2ActionPerformed
    
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        
       
       if(!validateEmpty())
       {
          create(); 
       }
       
    }//GEN-LAST:event_createButtonActionPerformed
    
    /*public void validateNumber(int zc, int contact,int year1, int year2,double cgp1,double cgp2)
    {
        if(!JZipCodeTextField.getText().matches(".*\\d.*"))
        {
          JOptionPane.showMessageDialog(null,"Please enter valid zipcode including only numbers.");  
        }
    
     
    }*/
    public void create()
    {
        
        
        String fname=JFirstNameTextField.getText();           
        String lname=JLastNameTextField.getText();        
        String addr1=JAddressLineTextField.getText();
        String addr2=JAddressLine2TextField.getText();
        String city=JCityTextField.getText();
        String state=JStateTextField.getText();
        String country=countryTextField.getText();
        
        /*try //zipcode start
        {
            
         if(!JZipCodeTextField.getText().trim().isEmpty())
        {
            if(firstRadioButtonUS.isSelected())
            {
              if(JZipCodeTextField.getText().length()>5)
              {
                  JOptionPane.showMessageDialog(null,"Invalid Zip Code. Maximum length is five.");
                  
              }
            }
            zc= Integer.parseInt(JZipCodeTextField.getText());
        }
         
        }
        catch(NumberFormatException e)
        {
           JOptionPane.showMessageDialog(null,"Please enter valid zipcode including only numbers."); 
        }
        // zipcode end
        
        */
         
       
        
        String affiliation=affiliationTextField.getText();
        String careerObjective=JCareerObjectiveField.getText();
        String exp=experienceTextField.getText();
        
        String degName1=degreenameTextField1.getText();
        //degree1.setDegreeName(degName1);
        String degUniName1=degreeuniTextField1.getText();
        //degree1.setUniversity(degUniName1);
        //degree1.setYear(year1);
        //degree2.setYear(year2);
      
        /*  try
            {
        if(!degreecgpaTextField2.getText().trim().isEmpty())
           {
           
        cgp2= Double.parseDouble(degreecgpaTextField2.getText());
        // degree2.setCgpa(cgp2);
        /*if(cgp2>4.0)
        {
            JOptionPane.showMessageDialog(null,"Please enter valid CGPA2 on a scale of 4.0");
         }
        }
            }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,"Please enter valid CGPA on a scale of 4.0");  
        }*/
        /*  try
               
        {
            if(!degreeyearTextField2.getText().trim().isEmpty())
            {
         year2= Integer.parseInt(degreeyearTextField2.getText());
        //degree2.setYear(year2);
           /* if(degreeyearTextField2.getText().length()>4)
           {
              JOptionPane.showMessageDialog(null,"Please enter valid Year of Passing.Length cannot be greater than four!"); 
            }
           // }      
        }
        }catch(Exception e)
       {
            JOptionPane.showMessageDialog(null,"Please enter valid Year of Passing.");
        }*/
       
                   
          
        /*  try       
        {
           
        
         cgp1=Double.parseDouble(degreecgpaTextField1.getText());
        //degree1.setCgpa(cgp1);
       /*  if(cgp1>4.0)
        {
             JOptionPane.showMessageDialog(null,"Please enter valid CGPA on a scale of 4.0");
         }
        }catch(Exception exc)
        {
            JOptionPane.showMessageDialog(null,"Please enter valid CGPA on a scale of 4.0"); 
        }*/
        
        
         
        
        
        String degName2=degreenameTextField2.getText();
        //degree2.setDegreeName(degName2);
        String degUniName2=degreeuniTextField2.getText();
       // degree2.setUniversity(degUniName2);
        //degree1.setCgpa(cgp1);
        // degree2.setCgpa(cgp2);
        
            
        
        
       
                 /*    try//year1 start
                    {
                       
                   year1=Integer.parseInt(degreeyearTextField1.getText());
                  // degree1.setYear(year1);
                  /*  if(degreeyearTextField1.getText().length()>4)
                   {
                        JOptionPane.showMessageDialog(null,"Please enter valid Year of Passing.Length cannot be greater than four!"); 
                    degreeyearTextField1.setText("");
                   }
                  
                }catch(Exception ex)
        {
           JOptionPane.showMessageDialog(null,"Please enter valid Year of Passing.");
           degreeyearTextField1.setText("");
        }*///year 1 end
            
            
        
       
        
        
        String award=awardsTextField.getText();
        String proj=projTextField.getText();
        String participate=partiipateTextField.getText();
        String certi= certificationTextField.getText();
        String eid=emailidTextField.getText();
        /*try
        {
        if(!contactTextField.getText().trim().isEmpty())
        {
            if(contactTextField.getText().length()!=10)
            {
            JOptionPane.showMessageDialog(null,"Please enter valid contact number"); 
            }
            contact=Integer.parseInt(contactTextField.getText());
        }
            
        }catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,"Please enter valid contact number");   
        }*/
        
       Resume res=resume.addResume();
        
        
        System.out.println("path in "+path);        
        res.setPath(path);
        
        res.setLastName(lname);
        res.setFirstName(fname);
        res.setEmail(eid);
         
        res.setAddressLine1(addr1);
        res.setAddressLine2(addr2);
        res.setCity(city);
        res.setState(state);
        res.setCountry(country);      
        res.setZipCode(zc);
        res.setAffiliation(affiliation);
        res.setCareerObjective(careerObjective);
        res.setExperience(exp);
        //res.setDegree1(degree1);
        //res.setDegree2(degree2);
        res.setDegreeName(degName1);
        res.setUniversity(degUniName1);
        res.setYear(year1);
        res.setCgpa(cgp1);
        res.setDegreeName2(degName2);
        res.setCgp2(cgp2);
        res.setUniName2(degUniName2);
        res.setYear2(year2);
        res.setAchievements(award);
        res.setProjects(proj);
        res.setParticipations(participate);
        res.setCertifictions(certi);
        res.setContact(contact);
        
        
        //radio button functionality
        if(firstRadioButtonMale.isSelected())
        {
            res.setGender(firstRadioButtonMale.getText());
        }
       
            if(firstRadioButtonFemale.isSelected())
        {
            res.setGender(firstRadioButtonFemale.getText());
        }
        if(firstRadioButtonUS.isSelected())
        {
            res.setNationality(firstRadioButtonUS.getText());
        }
        if(firstRadioButtonInternational.isSelected())
        {
            res.setNationality(firstRadioButtonInternational.getText());
        }
        
        if(firstRadioButtonUndergrad.isSelected())
        {
            res.setType(firstRadioButtonUndergrad.getText());
        }
        if(firstRadioButtonGraduate.isSelected())
        {
            res.setType(firstRadioButtonGraduate.getText());
        }
        
        // checkbox code
       
        
        String skills="";
        if(checkBoxJava.isSelected())
        {
            skills= skills+ ""+ checkBoxJava.getText()+"\n";//JAVA
        }
        if(checkBoxC.isSelected())
        {
         skills= skills+ ""+ checkBoxC.getText()+"\n"; //C++  
        }
        if(checkBoxHtml.isSelected())
        {
            skills= skills+ ""+ checkBoxHtml.getText()+"\n"; //HTML
        }
        if(checkBoxCss.isSelected())
        {
            skills= skills+ ""+ checkBoxCss.getText()+"\n";//CSS
        }
        if(checkBoxPhp.isSelected())
        {
            skills= skills+ ""+ checkBoxPhp.getText()+"\n";//PHP
        }
        if(checkBoxSql.isSelected())
        {
            skills= skills+ ""+ checkBoxSql.getText()+"\n";//SQL
        }
        if(checkBoxPlsql.isSelected())
        {
            skills= skills+ ""+ checkBoxPlsql.getText()+"\n";//PL/SQL
        }
        if(checkBoxCsharp.isSelected())
        {
            skills= skills+ ""+ checkBoxCsharp.getText()+"\n"; //c#
        }
        if(checkBoxOthers.isSelected())
        {
            skills= skills+ ""+ othersTextField.getText()+"\n";
        }
        res.setSkills(skills);
        JOptionPane.showMessageDialog(null,"Resume created successfully!!");
         clear();
        
    }
    
  
    private void degreenameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreenameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreenameTextField1ActionPerformed

    private void checkBoxOthersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxOthersActionPerformed
        // TODO add your handling code here:
         if(checkBoxOthers.isSelected())
        {
            othersTextField.setVisible(true);
           
        }
         else
         {
             othersTextField.setVisible(false);
         }
    }//GEN-LAST:event_checkBoxOthersActionPerformed

    private void JFirstNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JFirstNameTextFieldFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JFirstNameTextFieldFocusGained

    private void JFirstNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JFirstNameTextFieldFocusLost
        // TODO add your handling code here:
        //JTextField tf=new JTextField();
        String fname=JFirstNameTextField.getText();
            if(fname.matches(".*\\d.*"))
            {
              
            JOptionPane.showMessageDialog(null,"You cannot enter Numbers in Name.");
            JFirstNameTextField.setText("");
        
            }
            int i;
        for(i=0; i<fname.length();i++)
        {
            if(fname.charAt(i)=='*' //if first name contains special characters
                    ||fname.charAt(i)=='/'
                    ||fname.charAt(i)=='@'
                    ||fname.charAt(i)=='!'
                    ||fname.charAt(i)=='#'
                    ||fname.charAt(i)=='%'
                    ||fname.charAt(i)=='$'
                    ||fname.charAt(i)=='('
                    ||fname.charAt(i)==')'
                    ||fname.charAt(i)=='_'
                    ||fname.charAt(i)=='.'
                    ||JFirstNameTextField.getText().trim().isEmpty()
                    )
                {
              JOptionPane.showMessageDialog(null,"You cannot enter special characters or whitespaces!");
              JFirstNameTextField.setText("");
              break;
             
            }
        }
        //tf.requestFocusInWindow();
    }//GEN-LAST:event_JFirstNameTextFieldFocusLost

    private void JLastNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JLastNameTextFieldFocusLost
        // TODO add your handling code here:
        String lname=JLastNameTextField.getText();  
            
            if(lname.matches(".*\\d.*"))
            {
              
            JOptionPane.showMessageDialog(null,"You cannot enter Numbers in Name.");
            JLastNameTextField.setText("");
        
            }
           
        for(int i=0; i<lname.length();i++)
        {
            if(lname.charAt(i)=='*' //if last name contains special characters
                    ||lname.charAt(i)=='/'
                    ||lname.charAt(i)=='@'
                    ||lname.charAt(i)=='!'
                    ||lname.charAt(i)=='#'
                    ||lname.charAt(i)=='%'
                    ||lname.charAt(i)=='$'
                    ||lname.charAt(i)=='('
                    ||lname.charAt(i)==')'
                    ||lname.charAt(i)=='_'
                    ||lname.charAt(i)=='.'
                    ||JLastNameTextField.getText().trim().isEmpty()
                    )
                {
              JOptionPane.showMessageDialog(null,"You cannot enter special characters!");
             JLastNameTextField.setText("");
              break;
             
            }
        }
    }//GEN-LAST:event_JLastNameTextFieldFocusLost

    private void contactTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactTextFieldFocusLost
        // TODO add your handling code here:
       try
        {
       
            if(!contactTextField.getText().trim().isEmpty())
            {
                contact= Long.parseLong(contactTextField.getText());
                if(contactTextField.getText().length()!=10)
                     {
                        JOptionPane.showMessageDialog(null,"Please enter valid contact number. Total characters should be 10");
                        contactTextField.setText("");
                        //return;
                      }
            
            }
            
        }catch(Exception e)
       {
         JOptionPane.showMessageDialog(null,"Please enter valid contact number"); 
          contactTextField.setText("");
       }
        
    }//GEN-LAST:event_contactTextFieldFocusLost

    private void contactTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactTextFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTextFieldMouseExited

    private void contactTextFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactTextFieldMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_contactTextFieldMouseReleased

    private void JZipCodeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JZipCodeTextFieldFocusLost
        // TODO add your handling code here:
        
        try
        {
            if(!JZipCodeTextField.getText().trim().isEmpty())
            {
                zc= Integer.parseInt(JZipCodeTextField.getText());
                if(firstRadioButtonUS.isSelected())
                {
                    if(JZipCodeTextField.getText().length()!=5)
                    {
                        JOptionPane.showMessageDialog(null,"Invalid Zip Code. Maximum length is five characters for United States.");
                        JZipCodeTextField.setText("");
                    }
                }
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Please enter valid zipcode");
            JZipCodeTextField.setText("");
        }
    }//GEN-LAST:event_JZipCodeTextFieldFocusLost

    private void degreeyearTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_degreeyearTextField1FocusLost
       try//year1 start
                    {
                       if(!degreeyearTextField1.getText().trim().isEmpty())
            { 
                   year1=Integer.parseInt(degreeyearTextField1.getText());
                  // degree1.setYear(year1);
                   if(degreeyearTextField1.getText().length()>4)
                   {
                        JOptionPane.showMessageDialog(null,"Please enter valid Year of Passing.Length cannot be greater than four!"); 
                    degreeyearTextField1.setText("");
                   }
            }
                }catch(Exception ex)
        {
           JOptionPane.showMessageDialog(null,"Please enter valid Year of Passing.");
           degreeyearTextField1.setText("");
        }//year 1 end
    }//GEN-LAST:event_degreeyearTextField1FocusLost

    private void degreeyearTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_degreeyearTextField2FocusLost
     try
               
        {
            if(!degreeyearTextField2.getText().trim().isEmpty())
            {
         year2= Integer.parseInt(degreeyearTextField2.getText());
        //degree2.setYear(year2);
           /* if(degreeyearTextField2.getText().length()>4)
           {
              JOptionPane.showMessageDialog(null,"Please enter valid Year of Passing.Length cannot be greater than four!"); 
            }*/
           // } */     
        }
        }catch(Exception e)
       {
            JOptionPane.showMessageDialog(null,"Please enter valid Year of Passing.");
        }
        
    }//GEN-LAST:event_degreeyearTextField2FocusLost

    private void degreecgpaTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_degreecgpaTextField1FocusLost
         try       
        {
            if(!degreecgpaTextField1.getText().trim().isEmpty())
            {
        
         cgp1=Double.parseDouble(degreecgpaTextField1.getText());
        //degree1.setCgpa(cgp1);
        if(cgp1>4.0)
        {
             JOptionPane.showMessageDialog(null,"Please enter valid CGPA on a scale of 4.0");
         }
            }
        }catch(Exception exc)
        {
            JOptionPane.showMessageDialog(null,"Please enter valid CGPA on a scale of 4.0"); 
        }
    }//GEN-LAST:event_degreecgpaTextField1FocusLost

    private void degreecgpaTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_degreecgpaTextField2FocusLost
       try
            {
        if(!degreecgpaTextField2.getText().trim().isEmpty())
           {
           
        cgp2= Double.parseDouble(degreecgpaTextField2.getText());
        // degree2.setCgpa(cgp2);
        if(cgp2>4.0)
        {
            JOptionPane.showMessageDialog(null,"Please enter valid CGPA2 on a scale of 4.0");
         }
        }
            }catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,"Please enter valid CGPA on a scale of 4.0");  
        }
    }//GEN-LAST:event_degreecgpaTextField2FocusLost

    private void JCityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JCityTextFieldFocusLost
        // TODO add your handling code here:
        String cityname=JCityTextField.getText();
            if(cityname.matches(".*\\d.*"))
            {
              
            JOptionPane.showMessageDialog(null,"You cannot enter Numbers in city name.");
            JCityTextField.setText("");
        
            }
            int i;
        for(i=0; i<cityname.length();i++)
        {
            if(cityname.charAt(i)=='*' //if first name contains special characters
                    ||cityname.charAt(i)=='/'
                    ||cityname.charAt(i)=='@'
                    ||cityname.charAt(i)=='!'
                    ||cityname.charAt(i)=='#'
                    ||cityname.charAt(i)=='%'
                    ||cityname.charAt(i)=='$'
                    ||cityname.charAt(i)=='('
                    ||cityname.charAt(i)==')'
                    ||cityname.charAt(i)=='_'
                    ||cityname.charAt(i)=='.'
                    ||JCityTextField.getText().trim().isEmpty())
                {
              JOptionPane.showMessageDialog(null,"You cannot enter special characters!");
              JCityTextField.setText("");
              break;
             
            }
        }
    }//GEN-LAST:event_JCityTextFieldFocusLost

    private void JStateTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JStateTextFieldFocusLost
        // TODO add your handling code here:
        String statename=JStateTextField.getText();
            if(statename.matches(".*\\d.*"))
            {
              
            JOptionPane.showMessageDialog(null,"You cannot enter Numbers in city name.");
            JStateTextField.setText("");
        
            }
            int i;
        for(i=0; i<statename.length();i++)
        {
            if(statename.charAt(i)=='*' //if first name contains special characters
                    ||statename.charAt(i)=='/'
                    ||statename.charAt(i)=='@'
                    ||statename.charAt(i)=='!'
                    ||statename.charAt(i)=='#'
                    ||statename.charAt(i)=='%'
                    ||statename.charAt(i)=='$'
                    ||statename.charAt(i)=='('
                    ||statename.charAt(i)==')'
                    ||statename.charAt(i)=='_'
                    ||statename.charAt(i)=='.'
                    ||JStateTextField.getText().trim().isEmpty())
                {
              JOptionPane.showMessageDialog(null,"You cannot enter special characters!");
              JStateTextField.setText("");
              break;
             
            }
        }
    }//GEN-LAST:event_JStateTextFieldFocusLost

    private void countryTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryTextFieldFocusLost
        // TODO add your handling code here:
        String countryname=countryTextField.getText();
            if(countryname.matches(".*\\d.*"))
            {
              
            JOptionPane.showMessageDialog(null,"You cannot enter Numbers in country name.");
            countryTextField.setText("");
        
            }
            int i;
        for(i=0; i<countryname.length();i++)
        {
                   if(countryname.charAt(i)=='*' //if first name contains special characters
                    ||countryname.charAt(i)=='/'
                    ||countryname.charAt(i)=='@'
                    ||countryname.charAt(i)=='!'
                    ||countryname.charAt(i)=='#'
                    ||countryname.charAt(i)=='%'
                    ||countryname.charAt(i)=='$'
                    ||countryname.charAt(i)=='('
                    ||countryname.charAt(i)==')'
                    ||countryname.charAt(i)=='_'
                    ||countryname.charAt(i)=='.'
                    ||countryTextField.getText().trim().isEmpty())
                {
              JOptionPane.showMessageDialog(null,"You cannot enter special characters!");
              countryTextField.setText("");
              break;
             
            }
        }
    }//GEN-LAST:event_countryTextFieldFocusLost

    private void emailidTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailidTextFieldFocusLost
        // TODO add your handling code here:
        String eid=emailidTextField.getText();
        int countAt=0;
        for ( int i=0; i< eid.length();i++)
        {
            if(eid.charAt(i)=='@')
            {
                countAt++;
            }
        }
       /* if(countAt!=1)
        {
            JOptionPane.showMessageDialog(null,"Enter valid email id!");
            emailidTextField.setText("");
        }*/
        String str= eid.substring(eid.indexOf('@')+1,eid.length());
        int countP=0;
        for(int i=0 ; i<str.length();i++)
        {
            if(str.charAt(i)=='.')
            {
                countP++;
            }
        }
        if(countP!=1 ||countAt!=1||eid.startsWith(".")||eid.startsWith("@")||emailidTextField.getText().trim().isEmpty())
        {
           JOptionPane.showMessageDialog(null,"Enter valid email id!");
           emailidTextField.setText("");
        }
        /*if(eid.startsWith(".")||eid.startsWith("@"))
        {
            JOptionPane.showMessageDialog(null,"Enter valid email id!");
           emailidTextField.setText(""); 
        }*/
    }//GEN-LAST:event_emailidTextFieldFocusLost

    private void firstRadioButtonMalePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_firstRadioButtonMalePropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_firstRadioButtonMalePropertyChange
    
    public boolean validateEmpty()
    {
      String firstName= JFirstNameTextField.getText();
        //System.out.println(firstName);
        if(firstName.trim().isEmpty()
                ||(JLastNameTextField.getText().trim().isEmpty())
                ||(JAddressLineTextField.getText().trim().isEmpty())
                ||(JCityTextField.getText().trim().isEmpty())
                ||(JStateTextField.getText().trim().isEmpty())
                ||(countryTextField.getText().trim().isEmpty())
                ||( String.valueOf(JZipCodeTextField.getText()).trim().isEmpty())
                ||(emailidTextField.getText().trim().isEmpty())
                ||(String.valueOf(contactTextField.getText()).trim().isEmpty())
                ||(degreeuniTextField1.getText().trim().isEmpty())
                ||(awardsTextField.getText().trim().isEmpty())
                || (projTextField.getText().trim().isEmpty())
                ||(partiipateTextField.getText().trim().isEmpty())
                ||(certificationTextField.getText().trim().isEmpty())
                ||(affiliationTextField.getText().trim().isEmpty())
                ||(JCareerObjectiveField.getText().trim().isEmpty())
                ||(experienceTextField.getText().trim().isEmpty())
                ||(degreenameTextField1.getText().trim().isEmpty())
                ||(degreeyearTextField1.getText().trim().isEmpty())
                ||(degreecgpaTextField1.getText().trim().isEmpty())
                ||JImage.getIcon()==null)
               // ||JYear.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Fields cannot be blank.Remember to upload your photograph also!");
          return true;
        }
        else
        {
            
            return false;
        }   
    }

    public void clear()
    {
        JFirstNameTextField.setText("");
        JLastNameTextField.setText("");
        JAddressLineTextField.setText("");
        JAddressLine2TextField.setText("");
        JCityTextField.setText("");
        JStateTextField.setText("");
        countryTextField.setText("");
        JZipCodeTextField.setText("");
        emailidTextField.setText("");
        contactTextField.setText("");
        othersTextField.setText("");
        degreecgpaTextField1.setText("");
        degreecgpaTextField2.setText("");
        degreeuniTextField2.setText("");
        degreeuniTextField1.setText("");
        degreenameTextField1.setText("");
        degreenameTextField2.setText("");
        degreeyearTextField1.setText("");
        degreeyearTextField2.setText("");
        
        awardsTextField.setText("");
        projTextField.setText("");
        partiipateTextField.setText("");
        certificationTextField.setText("");
        affiliationTextField.setText("");
        JCareerObjectiveField.setText("");
        experienceTextField.setText("");
        
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        
        checkBoxJava.setSelected(false);
        checkBoxC.setSelected(false);
        checkBoxCsharp.setSelected(false);
        checkBoxCss.setSelected(false);
        checkBoxHtml.setSelected(false);
        checkBoxPhp.setSelected(false);
        checkBoxPlsql.setSelected(false);
        checkBoxSql.setSelected(false);
        checkBoxOthers.setSelected(false);
        JImage.setIcon(null);
        othersTextField.setVisible(false);
        jScrollPane2.setBorder(null);
        
        firstRadioButtonMale.setSelected(true);
        firstRadioButtonUS.setSelected(true);
        firstRadioButtonGraduate.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JAddressLine2;
    private javax.swing.JTextField JAddressLine2TextField;
    private javax.swing.JLabel JAddressLine4;
    private javax.swing.JTextField JAddressLineTextField;
    private javax.swing.JButton JBrowse;
    private javax.swing.JTextArea JCareerObjectiveField;
    private javax.swing.JTextField JCgpa;
    private javax.swing.JTextField JCgpa1;
    private javax.swing.JTextField JCityTextField;
    private javax.swing.JTextField JDegree1Name;
    private javax.swing.JTextField JDegree1Name1;
    private javax.swing.JLabel JFirstNameLabel;
    private javax.swing.JTextField JFirstNameTextField;
    private javax.swing.JLabel JImage;
    private javax.swing.JLabel JLastName;
    private javax.swing.JTextField JLastNameTextField;
    private javax.swing.JTextField JStateTextField;
    private javax.swing.JTextField JUnivName;
    private javax.swing.JTextField JUnivName1;
    private javax.swing.JLabel JUnivNameLabel;
    private javax.swing.JTextField JYear;
    private javax.swing.JTextField JYear1;
    private javax.swing.JTextField JZipCodeTextField;
    private javax.swing.JLabel JyearLabel;
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JTextArea awardsTextField;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextArea certificationTextField;
    private javax.swing.JCheckBox checkBoxC;
    private javax.swing.JCheckBox checkBoxCsharp;
    private javax.swing.JCheckBox checkBoxCss;
    private javax.swing.JCheckBox checkBoxHtml;
    private javax.swing.JCheckBox checkBoxJava;
    private javax.swing.JCheckBox checkBoxOthers;
    private javax.swing.JCheckBox checkBoxPhp;
    private javax.swing.JCheckBox checkBoxPlsql;
    private javax.swing.JCheckBox checkBoxSql;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField degreecgpaTextField1;
    private javax.swing.JTextField degreecgpaTextField2;
    private javax.swing.JTextField degreenameTextField1;
    private javax.swing.JTextField degreenameTextField2;
    private javax.swing.JTextField degreeuniTextField1;
    private javax.swing.JTextField degreeuniTextField2;
    private javax.swing.JTextField degreeyearTextField1;
    private javax.swing.JTextField degreeyearTextField2;
    private javax.swing.JTextField emailidTextField;
    private javax.swing.JTextArea experienceTextField;
    private javax.swing.JRadioButton firstRadioButtonFemale;
    private javax.swing.JRadioButton firstRadioButtonGraduate;
    private javax.swing.JRadioButton firstRadioButtonInternational;
    private javax.swing.JRadioButton firstRadioButtonMale;
    private javax.swing.JRadioButton firstRadioButtonUS;
    private javax.swing.JRadioButton firstRadioButtonUndergrad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea othersTextField;
    private javax.swing.JTextArea partiipateTextField;
    private javax.swing.JTextArea projTextField;
    // End of variables declaration//GEN-END:variables
}
